### PR TITLE
Getting started docker

### PR DESCRIPTION
**Pull request by xdega**
Here it is. My first crack at some documentation on Docker integration for Laravel. 

This is a powerful new technology, with exceptional adoption rates, which I believe should be considered as a "getting started" option for hosting environment for Laravel projects. 

While the core concepts of Docker may have a bit of a learning curve, I have done a lot of the legwork to help make integration as simple as possible for users. Every bit as simple as Vagrant or Homestead, perhaps even easier in some respects.

I plan to actively maintain and develop the corresponding repository, along with this documentation.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I think this may be better suited as a blog post, etc.

**Comment by xdega** [comment]
@taylorotwell Well. I really want Laravel users to know this is an option, and a good one at that. But I certainly do not have access to a blog that has any kind of audience, hence the suggestion to place it in the Laravel docs along with the current options like Vagrant. I don't see much difference here.

If you have any suggestions on how I can actually reach an audience of Laravel users, I would certainly be interested in sharing the same information in blog post form. Again, though, I have no such access at this point.

**Comment by deleugpn** [comment]
@xdega start by posting it on Medium and submitting it to Laravel News through https://laravel-news.com/links

**Comment by xdega** [comment]
@deleugpn Thank you for the guidance. I will see what I can do, hopefully this is accepted by Laravel News, at least. 

I made some significant improvements to my implementation (https://github.com/xdega/laravel-with-docker), and was able to help someone completely new to Docker, get up and running in minutes. With minimal guidance.

As such, I wouldn't expect this to be a very long post.

**Pull request closed without merging**
