### PR TITLE
Change 'secret' to 'plain-text' everywhere where it means just a plain-text password

### PR DESCRIPTION
**Pull request by andreyst**
I was a bit disoriented by this and I guess little clarification would help.

### CODE REVIEW

**Comment by andreyst** [comment]
This was discussed earlier in https://github.com/laravel/docs/pull/1042.

**Comment by GrahamCampbell** [comment]
> just a plain-text password

You should not be encrypting user passwords this in this way.

**Comment by GrahamCampbell** [comment]
Hashing is not at all the same as encryption.

**Comment by taylorotwell** [comment]
Can you send this to master branch?

**Comment by andreyst** [comment]
@GrahamCampbell You're right, I shouldn't have use the word 'password'. Though it doesn't change anything about the actual PR. I've changed wording in the new PR.

@taylorotwell Sure, I reread guidelines and thought that this is a documentation for current stable release. Created a new PR.

**Pull request closed without merging**
