### PR TITLE
Recommend changing composer.json name after installation

### PR DESCRIPTION
**Pull request by LukeTowers**
See https://github.com/Roave/SecurityAdvisories/issues/81 for what sort of problems can arise if this change isn't made.

### CODE REVIEW

**Comment by taylorotwell** [comment]
This is not unique to just installing via Composer.

**Comment by LukeTowers** [comment]
@driesvints where would this be better located? Perhaps https://laravel.com/docs/8.x#initial-configuration?

**Comment by driesvints** [comment]
@LukeTowers I don't think Taylor wants to merge in anything at this time. Now that the issue with the advisory will be solved soon I think it's fine to leave things as is.

**Comment by LukeTowers** [comment]
Fair enough. I'd personally still recommending doing it regardless of installation method but it's up to you guys on that front. For @wintercms we'll probably introduce a post-install hook or command to do some cleaning tasks like that after install, or perhaps just make it a part of our install process through our CLI tool. @bennothommo see above FYI

**Pull request closed without merging**
