### PR TITLE
[6.x] Typo

### PR DESCRIPTION
**Pull request by pathak-vikash**
Laravel Cashier: Documentation:

Splling mistake for word Subscription.

### CODE REVIEW

**Comment by pathak-vikash** [comment]
@nunomaduro I'm checking the 5.8 documentation... the similar typo mistake was there as well. Should I submit another PR for that?
https://laravel.com/docs/5.8/billing

**Comment by nunomaduro** [comment]
@pathak-vikash Laravel 5.8 no longer receive fixes since `August 26th, 2019`. So I don't think is necessary.

**Comment by pathak-vikash** [comment]
@nunomaduro thanks! But here is another PR #5514  merged a few day's ago.  Also the same issue in `master` branch.
https://github.com/laravel/docs/blob/master/billing.md

**Comment by driesvints** [comment]
@pathak-vikash the 6.x branch will get merged into master so you don't need to pr that separately.

**Comment by vikash-aika** [comment]
Thanks @driesvints

**Comment by pathak-vikash** [comment]
Thanks @driesvints

**Pull request merged**
