### PR TITLE
documentation on default relationship models

### PR DESCRIPTION
**Pull request by browner12**
in reference to https://github.com/laravel/framework/pull/19733

### CODE REVIEW

**Comment by decadence** [comment]
What's about `HasOne`? Can you add note that `withDefault` is available for it? Or it is already somewhere in the docs?

**Comment by decadence** [comment]
Yep, there is no any mention about `withDefault` in docs.

**Comment by browner12** [comment]
@taylorotwell  thoughts on this? I didn't want to duplicate documenting the `withDefault` method under every relation it is available in.

What if I made a top level heading at the very bottom (under 'Touching Parent Timestamps') that could be a more general description of it, and which relations it was available for?  @sileence is working on it for some of the other relations right now, so then we could add them to the list when he's done.

**Comment by sileence** [comment]
It'd make sense to document the feature and mention the relations that support it. By the way here is the PR for morphOne https://github.com/laravel/framework/pull/19788.

**Comment by taylorotwell** [comment]
I don't really mind duplicating a basic example of it under both sections. I can tolerate duplication more in docs than code because it's more of a user assistance thing.

**Pull request merged**
