### PR TITLE
措辞一致

### PR DESCRIPTION
**Pull request by artiship**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We need an English commit message.

**Comment by montogeek** [comment]
Why @GrahamCampbell ?

**Comment by GrahamCampbell** [comment]
Every single other commit in here has an English commit message. Why would we not want an English commit message?

**Comment by montogeek** [comment]
I understand. So, he can amend the commit adding an English translation, like "Consistent wording".

**Comment by artiship** [comment]
我只是想说明，文档本身支持多语言是多么重要

**Comment by GrahamCampbell** [comment]
We don't support multiple languages. We ONLY officially document things in English.

**Comment by artiship** [comment]
https://github.com/laravel/docs/pull/1616

**Comment by GrahamCampbell** [comment]
The PR you've linked to was closed and not merged into our code?

**Comment by artiship** [comment]
I know, But I think maybe you should re-consider it seriously

**Comment by GrahamCampbell** [comment]
The decision was made ages ago, sorry.

**Comment by artiship** [comment]
Translation for Chinese, I'll help

**Comment by GrahamCampbell** [comment]
> Translation for Chinese, I'll help

We're not doing that. How many times do I need to say that?

**Comment by GrahamCampbell** [comment]
https://github.com/laravel-china/docs already exists anyway?

**Comment by artiship** [comment]
5.1 no progress, this is mine https://github.com/laragirl/docs, already 84 commits ahead

**Pull request merged**
