### PR TITLE
Mention deprecating McryptEncrypter

### PR DESCRIPTION
**Pull request by Carlsson87**
I know that you're specific about wording, so please rephrase as necessary.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Just use the encrypter contract.

**Comment by GrahamCampbell** [comment]
It doesn't matter what implementation is under the hood.

**Comment by Carlsson87** [comment]
In my case it did matter.

I have some strings that are encrypted using `McryptEncrypter` with `MCRYPT_RIJNDAEL_128`, and in the next release I wont be able to decrypt them anymore using `Encrypter` with `AES-128-CBC`. Or am I wrong about this? I would love to be wrong about this..

**Comment by GrahamCampbell** [comment]
That's kind of different though.

**Comment by GrahamCampbell** [comment]
This is wrong too.

**Comment by GrahamCampbell** [comment]
Look at the top of the list.

**Comment by GrahamCampbell** [comment]
It says the following deprecations will be removed in laravel 5.2.

**Comment by GrahamCampbell** [comment]
This will NOT be removed in 5.2.

**Comment by Carlsson87** [comment]
Allrighty then, thanks Graham.

**Pull request closed without merging**
