### PR TITLE
[7.x] Normalize style to PSR-2

### PR DESCRIPTION
**Pull request by voyula**
Normalize style to PSR-2.

https://www.php-fig.org/psr/psr-2/

> Control structure keywords MUST have one space after them; method and function calls MUST NOT.

### CODE REVIEW

**Comment by nunomaduro** [comment]
I prefer the current style in the docs.

**Comment by voyula** [comment]
@nunomaduro But this style is not consistent.
We can force single code style in Laravel.
This prevents mental complexity.

**Comment by voyula** [comment]
See: https://github.com/laravel/docs/blob/7.x/blade.md#if-statements

And see: https://github.com/laravel/docs/blob/7.x/blade.md#section-directives

This really not consistent.

Why two control structure keywords style different from each other.

**Comment by taylorotwell** [comment]
Looks bad. I literally never put spaces like that.

**Comment by taylorotwell** [comment]
Think about how you actually use PHP.

If I use the `count` function I don't do `count ($foo)`... I do `count($foo)`.

If I write an if statement I DO use a space `if ($foo)`

**Comment by voyula** [comment]
@taylorotwell Yeah, I too, i DO use a space when I use a control structure(like if, elseif etc.).

Documentation using space in some places, like "unless, isset, empty, etc.".

This documentation why not using space on all control structures(elseenv('testing') etc.)?

Is it not control structure? 😕

**Pull request closed without merging**
