### PR TITLE
[6.x] Cache Facade uses minutes but docs state seconds

### PR DESCRIPTION
**Pull request by owalerys**
Please see my comments in #5618 

The docs do not match up with the current implementation of the `Cache` Facade.

### CODE REVIEW

**Comment by owalerys** [comment]
image

**Comment by driesvints** [comment]
I think you're looking at an old Laravel version. 

Screen Shot 2019-11-21 at 15 51 25
Screen Shot 2019-11-21 at 15 51 59

**Comment by owalerys** [comment]
@driesvints my apologies, you're correct. I didn't realize that I was on 5.5. Thanks!

**Comment by driesvints** [comment]
@owalerys no worries

**Pull request closed without merging**
