### PR TITLE
[10.x ] Note new type-hints for Cast contracts

### PR DESCRIPTION
**Pull request by jasonmccreary**
There are a few more of these contract changes for Validation Rules. I'm starting with these to ensure this is something you want to add and then follow your formatting for the others.

### CODE REVIEW

**Comment by nunomaduro** [comment]
@taylorotwell For info, this change is optional. People don't have to change their applications. So, not sure if this should stay on the upgrade guide.

**Comment by jasonmccreary** [comment]
@nunomaduro, how is it optional? My understanding is if you implement an interface, you have to implement its type hints.

**Comment by nunomaduro** [comment]
It's called Covariance and Contravariance: https://www.php.net/manual/en/language.oop5.variance.php.

```php
interface CastsAttributes {
    function set(object $object, mixed $value);
}

class LowerCase implements CastsAttributes {
    function set($object, $value) {
        var_dump($object, $value);
    }
}

(new LowerCase)->set(new stdClass, 'value');
// object(stdClass) {},  string(5) "value"
```

**Comment by jasonmccreary** [comment]
Interesting, yeah, seems to only be if you define a type hint, then it needs to match. Otherwise, you can leave it off. Except for return types.

Oh, PHP.

**Pull request closed without merging**
