### PR TITLE
[8.x] Change to openswoole

### PR DESCRIPTION
**Pull request by mohprilaksono**
https://www.swoole.co.uk/

### CODE REVIEW

**Comment by taylorotwell** [comment]
I have no idea what all this open Swoole vs Swoole stuff is about tbh. Why should I choose one or the other?

**Comment by mohprilaksono** [comment]
@taylorotwell actually openswoole is a fork of the previous swoole extension since version v4.7.1, you can read about it here: 
https://www.getrevue.co/profile/openswoole/issues/we-are-now-open-swoole-812526

**Comment by taylorotwell** [comment]
Why should I use this instead of swoole?

**Comment by mohprilaksono** [comment]
The official documentation said that only support openswoole and only suitable for swoole extension version 4.7.1. also, in the installation process is using openswoole instead of swoole.
And i see Laravel octane recentely support both swoole and openswoole extension, 

https://github.com/laravel/octane/pull/407

But, maybe i should change this PR to support both? Like 'pecl install swoole or pecl install openswoole'?

**Pull request merged**
