### PR TITLE
Fix invalid class name

### PR DESCRIPTION
**Pull request by kokokurak**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No, this is correct as is.

**Comment by GrahamCampbell** [comment]
The other things around it are wrong, and need changing.

**Comment by kokokurak** [comment]
How is that correct? `use` statement calls unexisting class.

**Comment by GrahamCampbell** [comment]
> How is that correct? use statement calls unexisting class.

Yep. the import is wrong. But you changed the only bit that was correct to be wrong, see what I mean?

**Comment by kokokurak** [comment]
Hmm, it's not clear which is correct, it depends how we want to call the class: `PurchasePodcastCommand` (wrong `use`) or `PurchasePodcast` (wrong injection). I guess `PurchasePodcast` is better example for namespaced class, so I chose the latter.

**Comment by GrahamCampbell** [comment]
> Hmm, it's not clear which is correct

No, I'm telling you `PurchasePodcastCommand` is correct.

**Comment by kokokurak** [comment]
Can you explain why?

**Comment by kokokurak** [comment]
This doc: http://laravel.com/docs/5.0/bus also mentions `PurchasePodcast` command, not `PurchasePodcastCommand`.

**Comment by GrahamCampbell** [comment]
It needs the command suffix. Look at the source code, and you'll see why.

**Comment by GrahamCampbell** [comment]
> Can you explain why?

Just a convention.

**Pull request closed without merging**
