### PR TITLE
Improve code format

### PR DESCRIPTION
**Pull request by TENIOS**
When I was updating markdown for tables (https://github.com/laravel/docs/pull/9778) I noticed that the files with the new packages contain updated formatting of code blocks. They look better than the old ones because they have syntax highlighting, so you can immediately see any errors or incorrect indentation.

That's why I decided to reformat old code blocks with new ones while fixing both major errors and minor ones (absences, brackets, etc.). For example, you may find an unformatted block of code on the [Prompts](https://laravel.com/docs/11.x/prompts#:~:text=You%20may%20allow) (link with anchor) page:

Prompts

I understand and realize the significance of these changes, so I made them manually (no joke) not using macros or RegEx (it took me a day).

I realize that it will be difficult to test all the changes, but I would ask you to treat this as a new step in writing documentation.

You can see the changes without diff in my [fork repo](https://github.com/TENIOS/docs/tree/improve-code-format) or using the command in the `laravel.com` repository:
```
git clone --single-branch --branch "improve-code-format" https://github.com/TENIOS/docs "resources/docs/11.x"
```

P.S.: unfortunately English is not my native language so it is difficult for me to describe everything correctly and clearly.

### CODE REVIEW

**Comment by TENIOS** [comment]
By the way when I was doing tag design I found a second link tag, I checked and it is not used anywhere. Is this an echo of the past or just a typo? Either way I deleted it.

https://github.com/laravel/docs/blob/11.x/routing.md?plain=1#L556

**Comment by TENIOS** [comment]
Updated to the branch.

**Comment by taylorotwell** [comment]
It will be a long time before I have time to review every code block for accuracy, if ever. 😕

**Comment by spcbfr** [comment]
@TENIOS I'd suggest maybe splitting this PR into 3 or 4 smaller PRs. each one dealing with a specific problem. syntax highlighting, wrong number of tabs and missing code blocks seem to be the 3 main contenders

**Comment by TENIOS** [comment]
> @TENIOS I'd suggest maybe splitting this PR into 3 or 4 smaller PRs. each one dealing with a specific problem. syntax highlighting, wrong number of tabs and missing code blocks seem to be the 3 main contenders

After Tylor's words, I have my doubts about whether this PR has any place at all. I'm sorry about that, but my attempt had a place.

**Comment by TENIOS** [comment]
I have to close this PR because the changes come too often and constantly updating them until they are verified would not be the best way to go. I will make a couple of separate PRs to fix the bugs I found in the documentation and maybe publish the changed code blocks as separate files.

**Pull request closed without merging**
