### PR TITLE
Clarify where bug fixes should be sent

### PR DESCRIPTION
**Pull request by vlakoff**
Per "going off-topic" discussions:
* https://github.com/laravel/framework/pull/12046#issuecomment-180022125
* https://github.com/laravel/framework/pull/12173#issuecomment-180297611

If I recall correctly, these notes were written before LTS releases appeared.

### CODE REVIEW

**Comment by vlakoff** [comment]
Ah, and let's ping @GrahamCampbell :)

**Comment by GrahamCampbell** [comment]
Maybe we need to indicate that it must be an actual maintained branch. 4.0 for example has plenty of bugs in it that we're not fixing.

**Comment by vlakoff** [comment]
Agree, maybe "oldest supported branch" would be better.

**Comment by vlakoff** [comment]
Or "oldest maintained branch".

**Comment by vlakoff** [comment]
@taylorotwell I just noticed you only merged this change to 5.1, but haven't merged it to 5.2 nor master. You might want to do it, the 5.2 documentation being the one shown by default.

**Pull request merged**
