### PR TITLE
[9.x] Symfony Mailer breaking changes

### PR DESCRIPTION
**Pull request by deleugpn**
This is another part of https://github.com/laravel/framework/pull/40649 changing the documentation on how to work with AWS SES.

### CODE REVIEW

**Comment by taylorotwell** [comment]
We need to address this at the framework level. Seems kinda unacceptable from a DX perspective to require this on every mailable you send/

**Comment by driesvints** [comment]
I'll be working on a PR tomorrow for `symfony/amazon-mailer` so that originally functionality can be restored.

**Comment by deleugpn** [comment]
It's not as bad as it looks when you wrap the Mailer class with a decorator that knows that will be using SES and can apply the appropriate tag unconditionally.

The lack of tag support on Amazon Mailer for SES is kind of a bummer, but to be honest I actually liked how I managed to replace 5 Mailer config with just 1 + dedicated methods on my decorator to define the configuration set.

**Comment by taylorotwell** [comment]
@driesvints @deleugpn can this be closed in light of https://github.com/laravel/framework/pull/40696 ?

**Comment by deleugpn** [comment]
I will look into the Framework Pull Requests tomorrow or Monday and will report back. In the meantime, I will already go ahead and close this one. Thanks, everyone!

**Pull request closed without merging**
