### PR TITLE
[5.8] Added a section on testing webhooks locally.

### PR DESCRIPTION
**Pull request by danmatthews**
Just thought this might benefit folk who aren't used to the tooling and process surrounding developing with Webhooks.

### CODE REVIEW

**Comment by driesvints** [comment]
I'm not sure if a section here is warranted. I mean I get the why you would do it, just saying that I'm not sure it's the correct place.

**Comment by danmatthews** [comment]
Where do you think would be better suited?

**Comment by driesvints** [comment]
Maybe just point to Valet itself? I'm not sure that we should mention another tool if we already have one in the ecosystem.

**Comment by danmatthews** [comment]
Maybe just a note somewhere then? "{note} You can test webhooks locally using Laravel Valet and the valet share command"?

**Comment by driesvints** [comment]
@danmatthews that sounds good 👍

**Comment by danmatthews** [comment]
Do you think it's worth removing the section and just placing a note, or keeping the section?

**Comment by driesvints** [comment]
Just the note seems fine to me.

**Comment by danmatthews** [comment]
Updated - let me know if you think it would be better served elsewhere in the document.

**Pull request merged**
