### PR TITLE
Note on map callback

### PR DESCRIPTION
**Pull request by bmitch**

### CODE REVIEW

**Comment by bmitch** [comment]
Related to https://github.com/laravel/framework/issues/16376. Quick note to point out the callback needs to accept two parameters.

**Comment by taylorotwell** [comment]
It doesn't need to accept two parameters.

**Comment by taylorotwell** [comment]
Does this not work: `collect([1, 2, 3])->map(function ($x) { return $x * 2; });`

**Comment by bmitch** [comment]
@taylorotwell I don't think that works unless I'm not understanding it correctly. Take a look at https://github.com/laravel/framework/issues/16376

**Comment by adamwathan** [comment]
@bmitch Your issue in the other thread is that `intval` only accepts one parameter, and the `Collection::map` method passes both the value and the key to the callback, so PHP is trying to pass both parameters to `intval`, which is triggering your error.

In short, this:

```php
collect(['1', '2', '3'])->map('intval');
```

...is short for:

```php
collect(['1', '2', '3'])->map(function ($value, $key) {
    return intval($value, $key);
});
```

...which is why you are seeing the error.

Instead, what you want is this:

```php
collect(['1', '2', '3'])->map(function ($value, $key) {
    return intval($value);
});
```

...and since you aren't forced to actually accept the second parameter when you supply your own callback, so it's perfectly valid to write this instead:

```php
collect(['1', '2', '3'])->map(function ($value) {
    return intval($value);
});
```

It's a bit of a bummer that you can't just pass `intval` directly, but there's enough common use cases where people need the key when doing a map operation that I think this is the right trade off.

**Comment by bmitch** [comment]
Ah ok makes sense. Thanks for clearing that up @taylorotwell and @adamwathan !

**Comment by driade** [comment]
I just hit this in production with `map('intval')`. It would be great to have a short note in the docs warning that `map` passes both value and key to the callback, so native PHP callables with optional second parameters can behave unexpectedly. A small example recommending `fn ($value) => intval($value)` would probably save others from the same issue.

**Pull request closed without merging**
