### PR TITLE
fix withoutGlobalScope examples

### PR DESCRIPTION
**Pull request by jadjoubran**

### CODE REVIEW

**Comment by lagbox** [comment]
The docblock says it takes a string or a scope

    @param  \Illuminate\Database\Eloquent\Scope|string  $scope

**Comment by jadjoubran** [comment]
So would the `AgeScope::class` work?

**Comment by GrahamCampbell** [comment]
Both should be fine.

**Comment by lagbox** [comment]
Yes, the class constant returns a string.

**Comment by jadjoubran** [comment]
Then it seems I have a particular issue that's not making it work :fearful: 
Sorry for the noise

**Comment by lagbox** [comment]
No worries.
You may have an issue with namespacing.

**Pull request closed without merging**
