### PR TITLE
Remove legacy facades

### PR DESCRIPTION
**Pull request by Jarlskov**
Some of the facades mentioned in the docs has been removed from the framework.

### CODE REVIEW

**Comment by taylorotwell** [comment]
The queue one isn't legacy?

**Comment by Jarlskov** [comment]
The Interface havn't existed since 4.2 as far as I can see.

**Comment by taylorotwell** [comment]
It doesn't really need to be deleted though. It just need to be updated to the contract.

**Comment by taylorotwell** [comment]
I fixed it for you.

**Pull request merged**
