### PR TITLE
Typing error

### PR DESCRIPTION
**Pull request by eduardojunio**
Trying to access the id) attribute instead id.

### CODE REVIEW

**Comment by vlakoff** [comment]
The code was correct. This PR should be reverted.

**Comment by eduardojunio** [comment]
Correct? wtf?

**Comment by kaidesu** [comment]
Look at the placement of the parenthesis:

**(**'user_id', $request->user()->id**)**->get();

**Comment by eduardojunio** [comment]
Ohhh, yeah. xd

**Pull request merged**
