### PR TITLE
Corrected CACHE document

### PR DESCRIPTION
**Pull request by chynkm**
Updated Laravel Cache document content. Changed "seconds" to "minutes"

### CODE REVIEW

**Comment by driesvints** [comment]
This is incorrect. The cache component uses seconds instead of minutes.

**Comment by chynkm** [comment]
Please correct me if I am wrong, but the file Illuminate\Contracts\Cache\Repository interface mentions **minutes
Screenshot 2019-09-02 18 30 10
**

**Comment by driesvints** [comment]
@chynkm that seems to be an old version: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Contracts/Cache/Repository.php

**Comment by chynkm** [comment]
thanks

**Pull request closed without merging**
