### PR TITLE
Added note regarding the Laravel 4.2 HTML facade alias

### PR DESCRIPTION
**Pull request by chriskonnertz**
This is only a proposal. However, please add a note to the 5.0 upgrade guide that mentions the differences.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
This isn't true at all. You can alias it to what you want...

**Comment by GrahamCampbell** [comment]
It also doesn't matter, as class aliases are NOT case sensitive.

**Comment by chriskonnertz** [comment]
Hey @GrahamCampbell,

yes, one can alias it 'HTML' or 'HTML' or whatever. But that's not the point. The point is, if you upgrade the alias is 'HTML' as in 4.1, but the docs recommends to call it 'Html'. So one could name it 'Html' even though it's called 'HTML' in the application's "legacy" Blade templates.

**Comment by GrahamCampbell** [comment]
That's not a breaking change though, and is already obvious.

**Comment by GrahamCampbell** [comment]
Also, it's not been HTML by default for a long time.

**Comment by chriskonnertz** [comment]
It' 'HTML' since... I don't know, *forever*?

https://github.com/laravel/laravel/blob/v4.2.11/app/config/app.php#L169

**Comment by GrahamCampbell** [comment]
Over a year now.

**Comment by chriskonnertz** [comment]
Are we talking about the same topic?

The commit that added the alias notes is not a year old, it's from January:

https://github.com/laravel/docs/commit/3958a6ebd59639917e323ef097424832585721fe#diff-e6fbd6eb4a701f2e57b69c2f4696dbaeR190

**Comment by chriskonnertz** [comment]
Plus, the case matters. I can't tell you why at this moment. Have not figured it out yet.

**Comment by GrahamCampbell** [comment]
Case really doesn't. PHP's classes are not case sensitive.

**Comment by GrahamCampbell** [comment]
It would only matter for autoloading on a case sensitive filesystem, but aliased classes are not autoloaded...

**Comment by chriskonnertz** [comment]
I'm going to test it in another environment.

**Comment by chriskonnertz** [comment]
It's a general bug. I've created a DigitalOcean Droplet with Ubuntu and a LAMP-Stack. Uploaded my Laravel 5 application that follows the upgrade guide regarding the HTML facade. Check out these links:
http://46.101.171.248/ ('HTML')
http://46.101.171.248/test ('Html')

The only difference is the case. I still have no clue why it's a problem - **but it's a problem**.

**Comment by chriskonnertz** [comment]
@GrahamCampbell 
Still can't figure it out. Probably I've missed something - but what?

Tested it on Windows and Linux, with two Laravel projects. I cannot explain this to myself.

**Comment by GrahamCampbell** [comment]
PHP isn't case sensitive when it resolves classes.

**Comment by chriskonnertz** [comment]
Just found this old PR and could not hold me backing from replying. :D 

So I guess we are **both** right.

PHP does not care. It is not case senstive when it resolves classes.
But the _autoloader_ might be and I assume that this was the case here.

**Pull request closed without merging**
