### PR TITLE
Add SFTP driver configuration

### PR DESCRIPTION
**Pull request by mputkowski**
Reference: [#23308](https://github.com/laravel/framework/pull/23308)

### CODE REVIEW

**Comment by decadence** [comment]
Does it have `path` option?

**Comment by mputkowski** [comment]
@decadence it doesn't have. You can check all options [here](https://github.com/thephpleague/flysystem-sftp/blob/master/src/SftpAdapter.php#L54),

**Comment by decadence** [comment]
Actually it does. It's called `root`.

**Comment by mputkowski** [comment]
@decadence so why are you asking? You asked specifically of `path`, the answer is obvious...

**Comment by decadence** [comment]
I asked about option for specify path on server thinking it would have name path or whatever. Then I found root option for this.

**Pull request merged**
