### PR TITLE
Added tip to make using selenium-chrome-debug easier in sail

### PR DESCRIPTION
**Pull request by Patabugen**
I thought adding a tip to easily enable visualising Browser tests would be helpful (it'd have saved me a bunch of time today!). I've tried to get the wording/phrasing right this time - happy for any feedback!

### CODE REVIEW

**Comment by taylorotwell** [comment]
What do you mean by visualize? You mean actually open a browser?

**Comment by crynobone** [comment]
`sail dusk --browse` not available?

**Comment by Patabugen** [comment]
Yeah - I copied the phrasing in the selenioum docs (I also pondered wording it differently as "If you want to be able to watch the tests in a browser while they run do XYZ..." - assuming a little less knowledge of selenium-chrome-debug.

**Comment by Patabugen** [comment]
> 
> 
> `sail dusk --browse` not available?

Ah! Yes `--browse` does work (there's no mention of it anywhere in the docs - but I've found some details here: https://github.com/laravel/dusk/commit/4385eb40fffb9506d0a50f692c85940af5183b4b )

That's a useful way of setting `DUSK_HEADLESS_DISABLED` on a per-run basis, I could update the tip to suggest it.

**Comment by taylorotwell** [comment]
@Patabugen ah, cool. Yes, feel free to update the PR to reflect that. Is anything else necessary other than simply running `sail dusk --browse`?

**Comment by taylorotwell** [comment]
Feel free to resubmit when updated.

**Pull request closed without merging**
