### PR TITLE
[5.2] Separate explanation for default config value

### PR DESCRIPTION
**Pull request by vlakoff**
This might be improved by using an example apart from the base laravel config, but you get the idea.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I will adjust this on 5.3 branch.

**Comment by vlakoff** [comment]
bump :innocent:

> Have finished reading and updating every existing documentation page from top to bottom. Every sentence. Every word.

**Comment by vlakoff** [comment]
could this issue be reopened please?

**Comment by vlakoff** [comment]
Rebased to 5.6, no change was needed. Could this PR be reconsidered?

**Comment by vlakoff** [comment]
@taylorotwell Could this be reconsidered please? It's a small but helpful change :)

**Pull request closed without merging**
