### PR TITLE
Removed TelescopeServiceProvider without qualified namespace

### PR DESCRIPTION
**Pull request by moazam1**

### CODE REVIEW

**Comment by bonzai** [comment]
These are not the same service providers.

The one you want to remove extends `Laravel\Telescope\TelescopeApplicationServiceProvider`.

**Comment by paras-malhotra** [comment]
Neither should be removed. Both are needed for Telescope to work.

**Comment by paras-malhotra** [comment]
`Laravel\Telescope\TelescopeServiceProvider::class` needs to be removed as it does not require manual registration (is auto discovered in local).

**Comment by driesvints** [comment]
This is incorrect. It needs to be explicitly added in the service provider because these are instructions for a local only installation. With a local only installation the server provider isn't auto loaded because it shouldn't be available in production.

**Comment by paras-malhotra** [comment]
@driesvints with a local installation, the service provider is auto-loaded imo. Remember there are no instructions to add telescope to the `dont-discover` list and the Telescope package does register auto-loading as below:

https://github.com/laravel/telescope/blob/535889a7585c331854dbdf8ca5e66209588408dd/composer.json#L37-L43

**Pull request closed without merging**
