### PR TITLE
[9.x] Document advanced customisations

### PR DESCRIPTION
**Pull request by timacdonald**
See: 

- https://github.com/laravel/framework/pull/43620
- https://github.com/laravel/vite-plugin/pull/118

Tucked this away in a single spot throwing it all in a single example, try and de-emphasise it all - as it should only be for rare cases that this is even needed.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you switch to American English for consistency with rest of docs?

**Comment by taylorotwell** [comment]
@timacdonald fixed it - one thing I'm curious about...

> Within the `vite.config.js` file, you may then specify the same configuration:

Is this a *requirement* or is this an *alternative*?

**Comment by timacdonald** [comment]
Ahhh, dang. I actually thought I had done American spelling.

That is a requirement.

**Comment by timacdonald** [comment]
Just checked your commit. Apparently I didn’t know what spelling I wanted to use…and thought I’d mix it up 🥴

**Comment by garbinmarcelo** [comment]
Hi @timacdonald I have a question about "useBuildDirectory", I use it for the purpose of separating the assets from the painel and web parts. So far I've configured vite.config.js and vite.admin.config.js with different "useBuildDirectory" and it's working.

```js
export default defineConfig({
    plugins: [
        laravel({
            hotFile: 'build/painel.hot',
            buildDirectory: 'build/painel',
            input: [
                'resources/painel/app.scss',
                'resources/painel/app.js'
            ],
            ...
```

But I didn't understand very well how "useBuildDirectory" works in blade files with Livewire.

Example, I have 2 files, master.blade.php (which is the base of my layout) and another like login.blade.php

In the `master.blade.php` file I call Vite in the head of the file as follows:

```blade
{{ Vite::useHotFile('build/painel.hot')->useBuildDirectory('build/painel')->withEntryPoints(['resources/painel/app.scss', 'resources/painel/app.js']) }}
```



In the `login.blade.php` file I have the following asset:

```blade
{{ Vite::asset('resources/painel/media/svg/brand-logos/google-icon.svg') }}
```

In this case when I access the login page it returns: `Vite manifest not found at: /var/www/html/public/build/manifest.json`


but if I write at the beginning of the file:
```blade
{{ Vite::useBuildDirectory('build/painel') }}
```
in the `login.blade.php` file the page is rendered without any errors.

So my question is, is it necessary to use "Vite::useBuildDirectory" in all my `*.blade.php` files or is there a way to define this directory in a provider or even route (or even in my default layout which would be `master.blade.php`)?

Maybe this isn't the best place to ask this question, but I've been looking for this for a while and haven't found anything about my question.

Thank you for your attention and sorry for the inconvenience.

**Comment by timacdonald** [comment]
Hi there,

`Vite` is bound to the container as a singleton. Whenever you say `Vite::useBuildDirectory()`, it changes the set build directory that will be used for later calls.

If you have multiple builds but only reference one per request, you only need to call `Vite::useBuildDirectory()` once.

You may do it inline or even in a server provider.

If you are referencing multiple requests throughout the one request, then you are going to have to juggle this for each call.

If that is the case, I would recommend prefixing all calls with `useBuildDirectory` just to be safe.


```php
// you may call this anywhere, including a service provider or middleware...
Vite::useBuildDirectory('build-1');


Vite::asset('bar.png'); // 'build-1' build dir
Vite::asset('baz.png'); // 'build-1' build dir

Vite::useBuildDirectory('build-2');

Vite::asset('bar.png'); // 'build-2' build dir
Vite::asset('baz.png'); // 'build-2' build dir

// alternatively, if need to reference mutliple through a single request...

Vite::useBuildDirectory('build-1')->asset('bar.png'); // 'build-1' build dir
Vite::useBuildDirectory('build-2')->asset('baz.png'); // 'build-2' build dir

```

**Pull request merged**
