### PR TITLE
[8.x] Remove duplicate provider registration

### PR DESCRIPTION
**Pull request by abenettt**
Remove duplicate provider registration for Telescope.

### CODE REVIEW

**Comment by driesvints** [comment]
This isn't duplicate. This is needed for local only installs.

**Comment by abenettt** [comment]
But they are both inside the if statement and the only difference is the namespace that is being specified or am I getting this wrong?

**Comment by driesvints** [comment]
If you read the paragraph above you'll notice that this is about two different `TelescopeServiceProvider` classes.

**Comment by abenettt** [comment]
Ah indeed, I got that wrong, my bad.

**Pull request closed without merging**
