### PR TITLE
IronMQ branch fix

### PR DESCRIPTION
**Pull request by joshhornby**
Have to use 1.* branch has any other branch gives 404 error

See https://github.com/iron-io/iron_mq_php#branches

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No, `~1.5` is correct.

**Comment by joshhornby** [comment]
Doesn't work for me and dropping back down to 1.* did. Also this guide states using v1 http://www.sitepoint.com/ironmq-laravel-setup/

**Comment by GrahamCampbell** [comment]
https://github.com/iron-io/iron_mq_php/pull/55

> Doesn't work for me and dropping back down to 1.* did. Also this guide states using v1 

I don't think you understand what that operator does in composer.

**Comment by GrahamCampbell** [comment]
`1.*` is the same as `~1.5`, only `~1.5` says the min version MUST be `1.5.0` too. That's all.

**Comment by joshhornby** [comment]
My bad, learn something new every day :+1:

**Pull request closed without merging**
