### PR TITLE
[5.3] Add composer.json changes to Upgrade Guide

### PR DESCRIPTION
**Pull request by tzurbaev**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎

**Comment by tzurbaev** [comment]
@GrahamCampbell  Am I missing something? composer.json update is not required to upgrade from 5.2?

**Comment by GrahamCampbell** [comment]
We don't do this on any of the guides because it's already obvious. Infact, the guides specifically describe what to do after you change the version.

**Comment by tzurbaev** [comment]
But [Upgrading To 5.2.0 from 5.1](https://laravel.com/docs/5.3/upgrade#upgrade-5.2.0) contains this section :)

But ok, I'll close this, thanks for reponse.

**Comment by GrahamCampbell** [comment]
Does it? Hmmm, maybe this is fine then.

**Comment by GrahamCampbell** [comment]
We should probably point out people should bump their symfony deps in require-dev too.

**Pull request closed without merging**
