### PR TITLE
Changed the return value from "void" to "string"

### PR DESCRIPTION
**Pull request by chriskonnertz**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Merge conflicts?

**Comment by chriskonnertz** [comment]
Yeah, but why? I'm not familiar with merge conflicts in GitHub - I know that BitBucket visualizes the conflict but it seems that GitHub does not?

**Comment by chriskonnertz** [comment]
I close this to investigate.

**Comment by GrahamCampbell** [comment]
Likely because you didn't pull down changes from this repo before starting.

**Pull request closed without merging**
