### PR TITLE
The exist method no longer works for flysystem

### PR DESCRIPTION
**Pull request by timleland**
The 'exist' method not longer exists :). Flysystem changed it to 'has' http://flysystem.thephpleague.com/api/

### CODE REVIEW

**Comment by taylorotwell** [comment]
This isn't calling `exists` on Flysystem. It's hitting our own Flysystem adapter which DOES have an `exists` method. Did you try it?

**Comment by timleland** [comment]
@taylorotwell Yes and I received this error. Am I doing something wrong?
image

**Comment by taylorotwell** [comment]
Can you paste your EXACT code?

**Comment by timleland** [comment]
```
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use Storage;
use Response;
use File;

class AvatarController extends Controller
{
    public function show($id)
    {
        $image_path = '/user/' . $id . '/avatar.jpeg';
        if(Storage::exist($image_path)){
            $image = Storage::get($image_path);
        }else{
            $image_path = base_path().'/public/images/avatar_not_found.jpeg';
            $image = File::get($image_path);
        }

        $response = Response::make($image, 200);
        $response->header('Content-Type', 'jpeg');
        return $response;
    }
}
```

**Comment by taylorotwell** [comment]
This works for me out of the box on a fresh Laravel:

dd(Storage::exists('test'));

**Pull request closed without merging**
