### PR TITLE
Sync Accepts Boolean

### PR DESCRIPTION
**Pull request by alexhackney**
Adding a passage about the boolean on sync that could save some headaches.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Personally I don't find this very intuitive. If you just want to add records you should be using `attach`. Just my two cents.

**Comment by alexhackney** [comment]
If you try to attach a record that already exists it throws an exception. Sync does not, being able to sync without getting all the current records saves a step.

**Comment by alexhackney** [comment]
Another use case.
https://laracasts.com/discuss/channels/eloquent/belongstomany-and-wanted-duplicates

**Comment by felipefrancisco** [comment]
This is very useful when handling old and new values in the same sync operation. This should be in the docs.

**Pull request closed without merging**
