### PR TITLE
Include examples of put/delete methods for implicit controllers

### PR DESCRIPTION
**Pull request by susanBuck**
I had a student ask whether Implicit controllers support put/delete in addition to get/post. This doc is *somewhat* vague about this, saying `The method names should begin with the HTTP verb `. You could infer from this that all 4 HTTP verbs are supported, however, in the examples we see only show get/post, so you might second guess this inference. 

In this proposed file change, I'm suggesting adding examples of put/delete. 

Alternatively, you could not add these examples, and instead make the instructions more explicit saying something like `all 4 HTTP verbs (get, post, put, delete) are supported.`

### CODE REVIEW

**Comment by lagbox** [comment]
There are more than 4 http verbs.

**Comment by crynobone** [comment]
If Laravel decide to deprecate/remove `Route::controller()` (they are considering it at the moment) I don't think this changes need to be added.

**Comment by lagbox** [comment]
@crynobone good to hear

**Comment by susanBuck** [comment]
@lagbox which am I missing? Patch?

**Comment by susanBuck** [comment]
@lagbox I should clarify, I'm thinking specifically here of the http methods we see mentioned elsewhere in the docs (RESTful controllers, form spoofing, etc.).

**Comment by susanBuck** [comment]
@crynobone If they remove it, then this whole section will be removed. In the meantime, though, it'd still be an accurate change.  I guess this hinges on *when* they plan on removing it... tomorrow, next week, next month, etc. : )

**Comment by crynobone** [comment]
As far as things goes right now is that it going to be deprecated in 5.2 (release this month-ish), and based on how deprecation work in Laravel it going to be removed in 5.3 (release next June).

If this is the case, advertising something that would be missing in less than a year shouldn't happen.

**Comment by susanBuck** [comment]
@crynobone This is not suggesting an advertisement be added, just that the existing advertisement (which as of this writing is applicable) be clearer. 

Was just a question that was raised by a Laravel student who is reading the documentation today (not next month, or next June) and was unclear on how the codebase (today) worked.

**Pull request closed without merging**
