### PR TITLE
[8.x] Fix docblock

### PR DESCRIPTION
**Pull request by ErickZH**
- Add `\Illuminate\View\View for View`

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks

**Comment by ErickZH** [comment]
@driesvints Can I also send this to the 6.x branch?

**Comment by driesvints** [comment]
We aren't really updating the old docs but sure

**Comment by ErickZH** [comment]
@driesvints I am participating in the hacktoberfest do you think you can add the hacktoberfest-accepted label to this PR please

**Comment by driesvints** [comment]
We aren't adding any hacktoberfest labels because of the recent influx of spam prs.

**Comment by ErickZH** [comment]
@driesvints Thanks not problem 🤟

**Pull request merged**
