### PR TITLE
Make passport.md compatible with axois

### PR DESCRIPTION
**Pull request by Quezler**

### CODE REVIEW

**Comment by Quezler** [comment]
Part of #3044

**Comment by brunen9** [comment]
@Quezler, good job! I only want to point that instead of `window.Laravel.csrfToken` we can use just `Laravel.csrfToken`.

**Comment by Quezler** [comment]
Well sometimes (generally inside a vue file) it often has trouble recognizing some variables not prefixed with `window.`

And sometimes apps like PhpStorm even go as far as to mark it completely invalid, while it works in the background.

So that were the primary reasons, but then again, its just a pull request, so anything can change 😃

**Comment by taylorotwell** [comment]
Those aren't even the same headers?

**Comment by taylorotwell** [comment]
Axios will automatically send the CSRF token. There isn't any configuration that is needed in that regard.

**Comment by Quezler** [comment]
Oh? on a fresh Laravel 5.4 password's 'consume your own javascript' refuses to work without this code?

**Comment by Quezler** [comment]
(axios does send A header, but that is xsrf, with a c)

**Comment by taylorotwell** [comment]
What I'm saying is the docs talk about setting a CSRF header but then you are setting a totally different header in your example.

**Comment by taylorotwell** [comment]
Change the wording.

**Comment by Quezler** [comment]
What parts should i change?

**Comment by taylorotwell** [comment]
I'll do it.

**Comment by taylorotwell** [comment]
I fixed a bunch of other places where Vue resource was still being used.

**Comment by Quezler** [comment]
Correct me if i see it incorrectly, but i only see the changes i initially submitted, i don't see any changes from you?

**Comment by brunen9** [comment]
> Axios will automatically send the CSRF token. There isn't any configuration that is needed in that regard.

@taylorotwell, but it doesn't. Comments in `bootstrap.js` says about it too, and it is really confusing, cause Axios only sends `X-XSRF-TOKEN`. There are some questions at laracasts and stackoverflow about this problem.

**Comment by Quezler** [comment]
Could you provide links?

**Comment by brunen9** [comment]
@Quezler 
[Comments in bootstrap.js](https://github.com/laravel/laravel/blob/master/resources/assets/js/bootstrap.js#L22)
[StackOverflow](http://stackoverflow.com/questions/40808405/how-to-add-token-when-using-axios-to-send-an-ajax-request)
[Laracasts](https://laracasts.com/discuss/channels/vue/laravel-54-and-axios)

**Comment by Quezler** [comment]
The last link is exactly the problem i addressed in the PR ❤️

**Comment by monomichael** [comment]
@taylorotwell I think you omitted the fact that people have to do the tweak **manually** at this moment. 

Axios doesn't automatically include `X-CSRF-TOKEN` in the header (it sends `X-XSRF-TOKEN` instead). See https://github.com/laravel/passport/issues/256

We have to either change the documentation or merge https://github.com/laravel/laravel/pull/4128. What do you guys think?

**Comment by monomichael** [comment]
https://github.com/laravel/laravel/pull/4128

**Comment by brunen9** [comment]
I vote for code change so it will just work like it was with v-resource.

**Comment by Quezler** [comment]
What i personally do not like about axios is that the 400 range requires a custom function to allow up to the 500 range, else it will throw a huge error.

**Pull request merged**
