### PR TITLE
Update sanctum.md

### PR DESCRIPTION
**Pull request by TodoshiTakato**
Corrected and improved the "Issuing API Tokens" block where Laravel PHP code is given as an example

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why?

**Comment by TodoshiTakato** [comment]
Because User model class should first extend default Laravel model
'Illuminate\Database\Eloquent\Model',
then implement
'Illuminate\Contracts\Auth\Authenticatable' interface.

I think Class can not extend Interface. At least PHPStorm IDE is saying that 'Class reference expected',
and advices to "Change 'extends Authenticatable' to 'implements Authenticatable' "

**Comment by Jubeki** [comment]
In the laravel skeleton it also uses `extends Authenticatable` which is an alias:

```php
use Illuminate\Foundation\Auth\User as Authenticatable;
```

See https://github.com/laravel/laravel/blob/2254e8e301cfcbf8983c2f7cfa8b7c63549b73c7/app/Models/User.php#L7

**Comment by TodoshiTakato** [comment]
Oh, okay, thank you very much, I was wrong.

**Pull request closed without merging**
