### PR TITLE
Add note of the possibility to localize PasswordReset notifications

### PR DESCRIPTION
**Pull request by dakira**
I also added a complete example which might be a bit too much but should get people started more easily. This change depends on the acceptance of [this pull request](https://github.com/laravel/framework/pull/23885).

### CODE REVIEW

**Comment by BobbyBorisov** [comment]
hey @dakira i don't know but when i use "If you’re having trouble ..." key it does not translate it..any idea why

**Comment by dakira** [comment]
@BobbyBorisov You need to use the key exactly as it's used originalley: https://github.com/laravel/framework/search?q=having+trouble&unscoped_q=having+trouble

**Review by Hed86 — COMMENTED** [review]
Hi, 
egal was ich mache, die Zeile mit dem Link funktioniert einfach nicht:
"If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below into your web browser: [:actionURL](:actionURL)": "Wenn du Probleme mit dem \":actionText\"-Button hast kopiere einfach diese Adresse in deinen Browser: [:actionURL](:actionURL)",

hättest du eine Ahnung, woran es liegen könnte?

Vielen Dank im Voraus
Alan

**Comment by dakira** [comment]
@Hed86 This is not a forum and the accepted language is English. Also the answer to your question is in my previous comment (you're not escaping the quotes).

**Pull request closed without merging**
