### PR TITLE
Remove brackets from example

### PR DESCRIPTION
**Pull request by bobbybouwmann**
See #2715 

> Note: This issue doesn't exist in the 5.2 docs.. So not sure what happend here

### CODE REVIEW

**Comment by taylorotwell** [comment]
Brackets are fine.

**Comment by taylorotwell** [comment]
We should fix the root issue not modify the docs to satisfy broken behavior.

**Comment by jamesggordon** [comment]
@bobbybouwmann I had a deeper look at this issue and discovered that you can define a server alias to point to more than one server.

So this, for example, works:

    @servers(['web' => ['user@192.168.1.1', 'user@192.168.1.2']])

If you run **envoy run foo on web** it will run the task on both servers referred to by the "web" alias. This functionality is not mentioned in the Multiple Servers section of the docs.

If you were to run **envoy ssh web** (which, admittedly, doesn't make much sense) then you will get *Array to string conversion in envoy/src/Console/SshCommand.php on line 38*. Unfortunately, you also get the error even if you have only one server in the array. So I think the fix that Taylor really wants is a couple of checks when running the ssh command. (1) If the server is defined as an array but there is only one item, then pass that item into the ssh command and (2) if there are multiple servers defined in the array then throw an error. Seems like a lot of work for relatively little gain.

Personally, I think it makes more sense to disallow the syntax above, as it provides, IMO, very little extra benefit over and above the facility that is described in the Multiple Servers section, which also works nicely with the ssh command. However, if Taylor prefers it this way then who am I to argue. :smile:

The real test will be how many people lodge issues related to the ssh command not working when they define a server name within brackets and how many of those it takes before Taylor finally cracks and disallows the syntax above. :wink:

**Comment by bobbybouwmann** [comment]
@jamesggordon Thanks for explaining, learned something new today ;)

**Pull request closed without merging**
