### PR TITLE
[8.x] Add descriptions for Envoy notifications.

### PR DESCRIPTION
**Pull request by akikgt**
Hi, I added descriptions about how to pass a message to Envoy notification directives.
I think it would be useful to make it explicit.

### CODE REVIEW

**Comment by taylorotwell** [comment]
What happens if you don't pass this argument? If you pass it - does it overwrite any default message that Envoy would generate?

**Comment by akikgt** [comment]
If you don't pass this argument, it shows a default message.
For instance, the @slack's default message is `Runner ran a task.`
And yes, if you pass a message argument, it overwrites the default message.

**Comment by taylorotwell** [comment]
This would make people think they have to pass a message because it doesn't talk about that behavior of overwriting the default message.

**Comment by akikgt** [comment]
Thank you. I should've mentioned that a message is optional. I'll update the descriptions.

**Pull request closed without merging**
