### PR TITLE
Update pagination.md

### PR DESCRIPTION
**Pull request by iquad**
added "->toJson()"; to the Eloquent Query.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This actually isn't needed.

**Comment by iquad** [comment]
On my environment, it needed; trust me.

**Comment by GrahamCampbell** [comment]
Why?

**Comment by iquad** [comment]
@GrahamCampbell here is why -> https://gist.github.com/iquad/cd2e126ea557b023d133

**Comment by GrahamCampbell** [comment]
Laravel doesn't "echo" responses, so you're incorrect there. Please close this.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/1a7ee5a96754304df0c798969b96a2617a45a168/src/Illuminate/Routing/Router.php#L1030
https://github.com/laravel/framework/blob/1a7ee5a96754304df0c798969b96a2617a45a168/src/Illuminate/Http/Response.php#L36

**Comment by iquad** [comment]
@GrahamCampbell yeah mate sorry :\ I figured out when I used "return $data".

Have a nice day ^^

**Comment by GrahamCampbell** [comment]
Oh, right. Yeh, never, ever write `echo` in controller.

**Pull request closed without merging**
