### PR TITLE
Remove reference to "null" log driver that doesn't exist

### PR DESCRIPTION
**Pull request by amadeann**
There's no "null" driver for logging. There is only a "null" channel.

### CODE REVIEW

**Comment by browner12** [comment]
Before we get rid of this, can we add a section to discuss how to send logs to the "null" stack? It's still helpful information to know.

**Comment by amadeann** [comment]
@browner12 
I added this in my AppServiceProvider to get the `null` log functionality working:

```
use Monolog\Handler\NullHandler;
use Monolog\Logger as MonologLogger;

...

if (($logManager = $this->app->make('log')) instanceof LogManager) {
    $logManager->extend('null_driver', function ($app, array $config) {
        return new MonologLogger('null_driver', [
            new NullHandler,
        ]);
    });
}
```

but I think this is too much of a workaround for the docs. And then, having the driver named "null" is problematic, since there's no way I know of to define string `null` in `.env` file.

**Comment by browner12** [comment]
I wasn't suggesting a code change, just a docs blurb about how to use the "null" channel.

**Comment by amadeann** [comment]
I am not sure what note would be appropriate. This section
https://laravel.com/docs/10.x/logging#writing-to-specific-channels
already covers the topic of logging to a specific channel.

**Pull request merged**
