### PR TITLE
Clarification on accessing data inside a view when passing an array..

### PR DESCRIPTION
**Pull request by morganhein**
using the `view('app.view', $data)` format.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Using `this` as an example is confusing because PHP uses it to reference a class when you are within an object.

**Comment by morganhein** [comment]
Taylor, I thought about that. I'll update it and make it more clear.

**Comment by morganhein** [comment]
As you can see, i'm still learning to git.

**Comment by GrahamCampbell** [comment]
You must revert the change to the file permissions, and rebase and squash to one commit. Merge commits are not allowed.

**Pull request merged**
