### PR TITLE
Swap arguments on mergeConfigFrom and loadViewsFrom

### PR DESCRIPTION
**Pull request by barryvdh**
To account for changes in https://github.com/laravel/framework/commit/7b315aa752896ec8fb8a684f1c0b8f8a8cac2116

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
You missed one @barryvdh. See the duplicate I just closed.

**Comment by barryvdh** [comment]
Added

**Comment by daack** [comment]
Can be merged now??

**Pull request merged**
