### PR TITLE
[10.x] Explain max search results in Scout

### PR DESCRIPTION
**Pull request by driesvints**
See https://github.com/laravel/scout/issues/725

### CODE REVIEW

**Comment by joaopalopes24** [comment]
@driesvints Enjoy and update the documentation on the count macro.

PR: https://github.com/laravel/scout/issues/717

Remove:

```
Builder::macro('count', function () {
    return $this->engine()->getTotalCount(
        $this->engine()->search($this)
    );
});
```

Add:

```
Builder::macro('count', function () {
    $this->limit = 10;

    return $this->engine()->getTotalCount($this->raw());
});
```

**Comment by driesvints** [comment]
@joaopalopes24 can you send in a PR?

**Comment by joaopalopes24** [comment]
@driesvints Sure

**Comment by taylorotwell** [comment]
Gonna think a bit about how to incorporate this into docs.

**Pull request closed without merging**
