### PR TITLE
[5.8] Fix broken images

### PR DESCRIPTION
**Pull request by driade**
https://res.cloudinary.com/dtfbvvkyp/image/upload/v1537195039/photos/Test.png is broken

### CODE REVIEW

**Comment by driesvints** [comment]
Feel free to pr the correct one

**Comment by driade** [comment]
I'm sorry I don't have the original images. It seems you need to upload them to laravel.com, as seen on https://github.com/laravel/docs/pull/6307

I may suppose it's https://res.cloudinary.com/practicaldev/image/fetch/s--uWyniCqN--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://res.cloudinary.com/dtfbvvkyp/image/upload/v1537195039/photos/Test.png 

Same goes for 5.7 and 6.x

**Comment by driesvints** [comment]
@driade I re-opened your PR on 6.x

**Comment by driade** [comment]
Here you're the image. It' son my hand uploading it.

Test

**Comment by driesvints** [comment]
@driade we've removed the broken images from the readme of the repo as well so I think it's best to just remove them.

**Pull request closed without merging**
