### PR TITLE
Mention release notes

### PR DESCRIPTION
**Pull request by tillkruss**
Link release notes for a complete list of changes.

### CODE REVIEW

**Comment by taylorotwell** [comment]
We want to distinguish between the marketing release notes on the documentation page and the raw release notes.

**Comment by tillkruss** [comment]
Any suggestions? I just thought it would be nice to mention the raw release notes in the upgrade guide.

**Comment by taylorotwell** [comment]
I think we should put it at the top of the 5.4 release notes on the website.
>

**Comment by tillkruss** [comment]
Makes sense!

**Pull request closed without merging**
