### PR TITLE
Reference updating/adding APP_SERVICE key in .env file

### PR DESCRIPTION
**Pull request by DougThwaites**
Reopens #7511
References: laravel/sail#256

Opening a new PR as my wording/understanding was off in #7511.

Add reference to adding/updating an APP_SERVICE key in a users .env file after changing the laravel.test service image name.

The scenario behind this addition to the docs is a developer wanting a custom domain for there Sail project so they change the service image name in the docker-compose.yml file but then commands like `sail artisan` etc aren't proxied through to the correct application container and fail silently.

Thanks for your time team, appreciate the work everyone does.

### CODE REVIEW

**Comment by DougThwaites** [comment]
Sorry for wasting your time here Taylor, I obviously need to brush up on my Docker terminology/skills.

Thoughts on..

> remember to update your applications .env file to include an APP_SERVICE key with a value of your customized name to proxy commands through to the correct application container then:

**Comment by taylorotwell** [comment]
I don't know what to change about that entire section. It is only talking about changing an **image name** - it never instructs you to change the name of the `laravel.test` service in any way.

**Comment by taylorotwell** [comment]
If you are trying to access multiple applications at once - you should proxy them on different ports in your `docker-compose.yml`.

This entire section is only about having a unique **image** for each application.

**Comment by taylorotwell** [comment]
I removed any reference to `laravel.test` from that entire section. It isn't relevant.

**Comment by DougThwaites** [comment]
Cheers man, new wording looks thanks for spending time with me on this.

Merry Xmas from NZ

**Pull request closed without merging**
