### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by DCzajkowski**
I am pretty sure the time it takes to generate a hash **de**creases with the machine power increase ;)

### CODE REVIEW

**Comment by DCzajkowski** [comment]
I may be horribly wrong. I don't know what the intent was 😅

**Comment by DCzajkowski** [comment]
Maybe it should be rephrased:
> Bcrypt is a great choice for hashing passwords because its "work factor" is adjustable, which means that the **complexity of the** hash can be increased as hardware power increases.

**Comment by gmsantos** [comment]
@DCzajkowski in this context increased means the algorithm cost to hash a password.

I like the rephrase since time increase could lead to misunderstandings

**Comment by DCzajkowski** [comment]
Yeah, makes total sense!

**Pull request closed without merging**
