### PR TITLE
[5.7] Clarify foreign key constraint usage for SQlite

### PR DESCRIPTION
**Pull request by dakira**
When using SQLite enabling foreign key constraints in a migration has no
effect.

I also fixed an unescaped underscore, hope that's okay. :)

### CODE REVIEW

**Comment by taylorotwell** [comment]
It seems weird to make people do this?

**Comment by dakira** [comment]
@taylorotwell I agree 100%. In my opinion foreign key constraints should be enabled by default for SQLite. People who define constraints most probably want them enforced. If they never defined them, it doesn't make a difference if foreign key constraints are enabled.

If would make this configurable via a `database.connections.sqlite.foreign_keys` config key and enable it by default.

I'll gladly submit a PR for this and change this PR to a note that mentions the difference for sqlite.

**Comment by SjorsO** [comment]
Related: https://github.com/laravel/ideas/issues/1254

**Comment by driesvints** [comment]
Nice, I didn't know about this! I agree that we might perhaps better use a config option for this.

**Comment by taylorotwell** [comment]
Yeah I basically agree with that issue that a configuration option makes more sense.

**Pull request closed without merging**
