### PR TITLE
Docs for Typesense integration in Scout

### PR DESCRIPTION
**Pull request by jasonbosco**
@taylorotwell @driesvints This PR contains documentation for the recently merged Scout PR (https://github.com/laravel/scout/pull/773) that adds Typesense support to Scout.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Drafting until release day

**Comment by nickturrietta** [comment]
@jasonbosco, unless I'm mistaken this code does not work for modifying query parameters [1].

```php
use App\Models\Todo;
 
Todo::search('Groceries')->withSearchParameters([
    'query_by' => 'title, description'
])->get();
```

This was my solution fwiw.

```php
use App\Models\Todo;

tap(Todo::search('Groceries'), function($builder) {
    return $builder->model->searchableUsing()->withSearchParameters([
        'exclude_fields' => 'some_field_here',
    ]);
})->get();
```

[1] https://laravel.com/docs/10.x/scout#typesense-dynamic-search-parameters

**Comment by jasonbosco** [comment]
CC: @karakhanyans - please see @nickturrietta's comment above.

**Comment by jasonbosco** [comment]
@nickturrietta This issue has been fixed here: https://github.com/laravel/scout/issues/791

The method signature is slightly different now: 

```php
use App\Models\Todo;
 
Todo::search('Groceries')->options([
    'query_by' => 'title, description'
])->get();
```

**Pull request merged**
