### PR TITLE
Added Overriding Broadcast Queue Name to 5.2 docs

### PR DESCRIPTION
**Pull request by jonnywilliamson**
As per Taylor's request:

https://github.com/laravel/framework/pull/9869#issuecomment-167444050

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please could you send this to the 5.1 docs?

**Comment by jonnywilliamson** [comment]
@GrahamCampbell 

I think I've done that right for you.

**Comment by GrahamCampbell** [comment]
This PR can be closed then. ;)

**Comment by GrahamCampbell** [comment]
We will do 5.1->5.2->master branch merges.

**Comment by GrahamCampbell** [comment]
Eventually, lol.

**Pull request closed without merging**
