### PR TITLE
Fixing regression, links() to render()

### PR DESCRIPTION
**Pull request by JesseLeite**
This would need to be merged into both 5.2 and master branches.  Not sure how much of this doc has regressed... might be worth looking into?

### CODE REVIEW

**Comment by taylorotwell** [comment]
What was wrong with the docs? ->links() is valid in 5.2?

**Comment by JesseLeite** [comment]
I went to use `links()` and method doesn't exist.  Found this in upgrade guide for 5.0:

upgrade

Docs for 5.0 and 5.1 reflect this.  Docs for 5.2 regressed to `links()`.

**Comment by taylorotwell** [comment]
I see the "links" method in 5.2. I added it.

http://d.pr/i/1lQVb/5FSDMhF7

**Comment by JesseLeite** [comment]
Oh my bad!  I thought this app was 5.2, I haven't upgraded this one whoops.

Anyway, both are viable then.  Okay thanks :P

**Comment by taylorotwell** [comment]
:P

**Pull request closed without merging**
