### PR TITLE
->cron example

### PR DESCRIPTION
**Pull request by AlexeyMez**
It should be `->cron('* * * * *') instead of ->cron('* * * * * *')` I guess

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No?

**Comment by danieliancu** [comment]
The PR is correct, but the comment isn't.

There are 5 stars in cron: minute, hour, day of the month, month, day of the week.

**Comment by AlexeyMez** [comment]
Sorry, there is a mistake in comment. The problem is there are six asterix in documentation, but it should be five.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/docs/pull/1950.

**Comment by danieliancu** [comment]
@GrahamCampbell You are correct.

Looking at https://github.com/laravel/framework/blob/5.2/src/Illuminate/Console/Scheduling/Event.php clearly reflects that it has been implemented with 6 arguments, maybe the first one is for seconds?

I find it very confusing because the Linux cron is implemented with 5 arguments. I'll discuss it on Slack.

**Comment by taylorotwell** [comment]
There is an optional 6th "year" argument available: http://www.nncron.ru/help/EN/working/cron-format.htm

**Comment by danieliancu** [comment]
@taylorotwell thanks for the pointer.

**Comment by AlexeyMez** [comment]
Thanks for the explanation.

**Pull request closed without merging**
