### PR TITLE
changes to config/app.php cipher

### PR DESCRIPTION
**Pull request by Kryptonit3**
changes to config/app.php cipher

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This isn't quite true.

**Comment by GrahamCampbell** [comment]
You need to say, IF you were using that cipher, change it to that.

**Comment by GrahamCampbell** [comment]
And if you were using the 256 one, change it to that.

**Comment by taylorotwell** [comment]
I'll get this updated.

**Comment by Kryptonit3** [comment]
If everyone can use a different cipher then why wasn't the one from 5.0 working? Didn't know you could choose your cipher.

**Comment by GrahamCampbell** [comment]
> If everyone can use a different cipher then why wasn't the one from 5.0 working? Didn't know you could choose your cipher.

You can't. We only support two ciphers and that's it.

**Comment by GrahamCampbell** [comment]
We support the one that was the default in laravel 4, and we support the one that's currently the default, and that's it.

**Pull request closed without merging**
