### PR TITLE
Don't say simply

### PR DESCRIPTION
**Pull request by jameshfisher**
Created with https://github.com/jameshfisher/dont-say-simply

### CODE REVIEW

**Comment by taylorotwell** [comment]
Haha, looks pretty good overall.

**Comment by browner12** [comment]
simply wonderful.

**Comment by DojoGeekRA** [comment]
> simply wonderful

Simply the best reply 🤣

**Comment by jameshfisher** [comment]
🎉

**Comment by jameshfisher** [comment]
This was my first attempt at using my automated "simply" remover. Glad it was well-received - I appreciate I didn't provide much context for it!

**Pull request merged**
