### PR TITLE
[9.x] Add note to restart computer after upgrading Valet

### PR DESCRIPTION
**Pull request by driesvints**
This might be necessary sometimes. See https://github.com/laravel/valet/issues/1228

### CODE REVIEW

**Comment by taylorotwell** [comment]
This feels kinda janky? Not sure I want to recommend this without an understanding of why it's recommended so we can explain it.

**Comment by driesvints** [comment]
@taylorotwell we haven't figured out the exact reason for this since it's only happening on some machines (including mine) after upgrading to Valet v3. Rebooting fixes the certification issues. I feel like this isn't much to ask from people to upgrade.

Pinging @mattstauffer to help explain

**Comment by mattstauffer** [comment]
I agree it's janky. We don't have a better solution yet but I will try to dig into it tonight; hopefully I can downgrade my valet then upgrade again and repro the issue.

**Comment by driesvints** [comment]
Sent in https://github.com/laravel/valet/pull/1230 as an alternative.

**Pull request closed without merging**
