### PR TITLE
Updated Docs to use proper links to v4.1 files

### PR DESCRIPTION
**Pull request by msurguy**
Otherwise you are linking to "master" which is current stable branch (5.0)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This isn't right anyway. You should be linking to the last 4.1 tag on that repo.  v4.1.27

**Comment by msurguy** [comment]
@GrahamCampbell ok, do you want me to update the PR and re-submit it?

**Comment by msurguy** [comment]
Ping @GrahamCampbell and @taylorotwell ... What would you like me to do? The links are still 404-ing!

**Comment by taylorotwell** [comment]
Resubmit it. Sorry didn't notice Graham's comment when he made it.

**Pull request closed without merging**
