### PR TITLE
Fixed wrong type in Request docs

### PR DESCRIPTION
**Pull request by rudifrudi**
Methods 'only' and 'except' accept an array. See
http://laravel.com/api/5.1/Illuminate/Http/Request.html#method_only and
http://laravel.com/api/5.1/Illuminate/Http/Request.html#method_except.

### CODE REVIEW

**Comment by 2tunnels** [comment]
As you can see here: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Http/Request.php#L295 `only` method can accept not only an array. Mby docblock should be updated.

**Comment by rudifrudi** [comment]
I stand corrected! Fact remains though that the 'only' method still doesn't accept multiple parameters, so it should be an array in the docs.

**Comment by 2tunnels** [comment]
It does accept multiple parameters.

If you pass array, array will be used. If you pass multiple parameters, they will be converted into array.

http://php.net/manual/en/function.func-get-args.php

**Comment by rudifrudi** [comment]
Wow, I seem to have lost my glasses this morning. Sorry. You're totally right. I'll close the pull request :) :+1:

**Pull request closed without merging**
