### PR TITLE
Accessing Route Model Bindings in Middleware

### PR DESCRIPTION
**Pull request by viraj-khatavkar**
Documentation doesn't contain any information regarding the above use-case. I had to google it quite a few times for many of my apps. I think this would deserve a place in the docs.

### CODE REVIEW

**Comment by lagbox** [comment]
You can access route params from the Request as property `$request->param`. The `__get` method calls to `route` as the fallback. One should not do it this way but you 'can'.

**Comment by viraj-khatavkar** [comment]
@lagbox In middleware you cannot - I have tried it :)

**Comment by lagbox** [comment]
Im sorry that you can't but it works as I described. 
I can demonstrate this works as expected from a fresh 5.3 install.

**Comment by GrahamCampbell** [comment]
> In middleware you cannot - I have tried it :)

Yes you can, provided your middleware is run **after** the binding middleware.

**Comment by lagbox** [comment]
Even if it was before the binding middleware you can still get the original parameter from the request via the dynamic property (assuming there are no inputs with the same name).

**Comment by taylorotwell** [comment]
It depends on where your middleware is located in the stack.

**Pull request closed without merging**
