### PR TITLE
[7.x] Update mail.md

### PR DESCRIPTION
**Pull request by CiiDyR**
Add some missing DocBlock parameters.

### CODE REVIEW

**Comment by driesvints** [comment]
Please use FQN, thanks.

**Comment by CiiDyR** [comment]
Shouldn't @var also use FQN then? This is why I didn't write the @param's as FQN

**Comment by driesvints** [comment]
@CiiDyR it should yes. All docblocks across all Laravel projects should use FQN.

**Comment by CiiDyR** [comment]
I've created a new PR (#6189) that updates the docs where it was missing FQN.

**Pull request merged**
