### PR TITLE
[Cashier] Missing mandatory parameters to downloadInvoice

### PR DESCRIPTION
**Pull request by matthieumota**
I think there is a little typo about `downloadInvoice()`, method needs `data` array parameter with at least `vendor` and `product` keys.

### CODE REVIEW

**Comment by driesvints** [comment]
This isn't correct. In the latest v13 these aren't required anymore.

**Comment by matthieumota** [comment]
I suspected because I had seen the modification on the documentation. But I haven't found this anywhere in code base on [13.x](https://github.com/laravel/cashier-stripe/blob/13.x/src/Concerns/ManagesInvoices.php#L225) branch. Maybe I missed it.

**Comment by driesvints** [comment]
@matthieumota I'm sorry but you're correct. This is still required. I forgot to assign new defaults while working on v13 🤦‍♂️

**Comment by matthieumota** [comment]
I'm ok to open PR but I don't know what default values to product and vendor, maybe `APP_NAME` or empty value ?

**Comment by driesvints** [comment]
I'll take care of it in the next release 👍

**Pull request merged**
