### PR TITLE
Update upgrade.md

### PR DESCRIPTION
**Pull request by KevinMellott91**
Added migration instructions for the addition of the 'SoftDeletingTrait' alias, when upgrading from 4.1 to 4.2.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1: This isn't correct and 4.2 isn't maintained anymore anyway.

**Comment by taylorotwell** [comment]
Graham, what is correct?

**Comment by GrahamCampbell** [comment]
You don't HAVE to add this alias to upgrade so that's why I'm saying this is wrong. :)

**Comment by KevinMellott91** [comment]
Fair enough - thanks for the quick response

**Pull request closed without merging**
