### PR TITLE
Update class references

### PR DESCRIPTION
**Pull request by akshayagarwal**
Use the class constant syntax as in the code of Laravel 5.1

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What is it with people's obsession with this?

**Comment by akshayagarwal** [comment]
Forgive me, but is this a wrong PR? Maybe providing a reason for closing might help future contributors like me to understand the issue and submit better requests.

Simply mentioning that people are obsessed with a syntax is not helpful IMHO, especially if one can see that syntax being followed in the code. Sorry if I am missing something here.

**Comment by GrahamCampbell** [comment]
The reason is it just doesn't need changing.

**Comment by akshayagarwal** [comment]
Please tell me if you really believe that comment explained anything rationally.

If a new developer (in context with Laravel framework only) is reading the documentation, is it better if he sees an older version of code style?

**Comment by akshayagarwal** [comment]
I created a similar PR here https://github.com/barryvdh/laravel-ide-helper/commit/afe1fe88bae7309b88ec27940240c8bd23b731e8 which was duly merged.

I am no one to suggest the same approach be followed here but I think the reason to not merge can be something better than " it doesn't need changing "

**Comment by GrahamCampbell** [comment]
@taylorotwell lol

**Comment by montogeek** [comment]
Madness.

**Pull request merged**
