### PR TITLE
Document limiting client access to scopes in Passport

### PR DESCRIPTION
**Pull request by axlon**
https://github.com/laravel/passport/pull/1682

### CODE REVIEW

**Comment by bram-pkg** [comment]
I just found the PR which merged this functionality after a long search for existing functionality. Any updates on this documentation PR?

**Comment by hafezdivandari** [comment]
@axlon why not update the migrations on Passport and add `scopes` column to the `oauth_clients` table by default?

**Comment by axlon** [comment]
> @axlon why not update the migrations on Passport and add `scopes` column to the `oauth_clients` table by default?

@hafezdivandari this is definitely possible and might even be preferable now with strict mode, I didn't opt to do this at the time because grant_types was already an opt-in feature within passport that worked the same way (it also wasn't a part of the schema by default)

**Comment by driesvints** [comment]
Hi there. We'd released v11 now. Please re-send this to 11.x if you still want to get this in. Thanks.

**Pull request closed without merging**
