### PR TITLE
[8.x] Add documentation for including chains in batches

### PR DESCRIPTION
**Pull request by Orrison**
This adds documentation for the upcoming feature of including chains in batches.

### CODE REVIEW

**Comment by taylorotwell** [comment]
It isn't released yet.

**Comment by Orrison** [comment]
@taylorotwell I believe this was released, would this be able to be brought in? In the future before a release is it that I need to make the Pull Request to `master`?

**Comment by driesvints** [comment]
@Orrison no, master is for the next major release. Taylor meant that this should only be included once the version is tagged that includes this feature.

**Comment by Orrison** [comment]
Hey @driesvints oh gotcha! I will make sure I wait next time.

It does look like this has been tagged and released in `8.10` now: https://laravel-news.com/laravel-8-10-0

**Comment by taylorotwell** [comment]
This is already documented:

image

**Pull request closed without merging**
