### PR TITLE
Document installation of MongoDB

### PR DESCRIPTION
**Pull request by Shelob9**
#3047

### CODE REVIEW

**Comment by taylorotwell** [comment]
I wasn't even aware Homestead supports Mongo officially. To me it is something that should be managed in the `after.sh` script.

**Comment by svpernova09** [comment]
We do support MongoDB via https://github.com/laravel/homestead/pull/424

Seemed like it was one of those "Well it's easy enough why not". We should probably reopen/accept this PR.

**Comment by vesper8** [comment]
I wish I had known that Homestead supported MongoDB out of the box, I went through some pains installing it and will definitely be using it by having homestead manage it in the future. I had to search the issues on the Laravel Homestead repo to find out that it was already in there.. never thought to look in the scripts section.

If the support is already in then it should be made known that it's an option.

I just destroyed my box and recreated it with mongodb:true

I also modified the install script so it installs 3.4.x instead of 3.2

It worked perfectly.

the only thing though is that the installation instructions from this unmerged PR mention that if you install mongodb it will REPLACE mysql which is not the case.. and good thing too because I definitely want to use both mongodb and mysql. I guess the docs were copy/pasted from the mariadb instructions which is why it says that

**Comment by DFurnes** [comment]
Agreed! I think anyone using [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) would really appreciate this being better documented. I only stumbled upon it when peeking into the Homestead repository on a whim.

**Comment by deadlybutter** [comment]
👍 Would be nice to have this on the official documentation

**Pull request closed without merging**
