### PR TITLE
Constructor docblock should return self (PHPStorm warning)

### PR DESCRIPTION
**Pull request by pfuhrmann**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
PHPStorm is talking **** I'm afraid. `void` is the correct return type here.

**Comment by pfuhrmann** [comment]
I agree that `void` is technically correct. However it MAY be omitted as per phpDoc guidelines which would be compromise and people using code examples in PHPstorm will be less confused and warning free.

> functions and methods without a `return` value, the @return tag MAY be omitted here, in which case @return void is implied
http://phpdoc.org/docs/latest/references/phpdoc/tags/return.html

**Comment by GrahamCampbell** [comment]
PHPStorm need to fix this, not us.

**Comment by taylorotwell** [comment]
It says that @return self is implied for constructors, which actually would
mean our stuff is wrong?

**Comment by GrahamCampbell** [comment]
> It says that @return self is implied for constructors, which actually would mean our stuff is wrong?

Those docs are wrong. The current phpdoc standard doesn't say that. Those docs quoted there are from like 10 years ago.

**Comment by pfuhrmann** [comment]
Can you please send link for current docs?

**Comment by GrahamCampbell** [comment]
https://github.com/php-fig/fig-standards/pull/169

**Comment by GrahamCampbell** [comment]
https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md

**Comment by GrahamCampbell** [comment]
Also, it doesn't really matter what any of these standards say anyway, when the offical php documentation already defines what void means for us.

**Pull request closed without merging**
