### PR TITLE
[7.x] Consistent filename

### PR DESCRIPTION
**Pull request by winter-ice**
We should keep consistent filename both in `artisan make:model Model -a` and `artisan make:seeder Seeder`.
Or edit the source code:
https://github.com/laravel/framework/blob/095ab36cabb942301ddc2060b3dbf1550474f4d8/src/Illuminate/Foundation/Console/ModelMakeCommand.php#L112

### CODE REVIEW

**Comment by driesvints** [comment]
We'll need to update the skeleton as well then.

**Comment by winter-ice** [comment]
@driesvints 
Sorry, I can't understand your comment.
Is there anything else I need to do?

**Comment by driesvints** [comment]
@winter-ice https://github.com/laravel/laravel/blob/master/database/seeds/DatabaseSeeder.php#L14

**Comment by winter-ice** [comment]
Should I make a PR for this?

**Comment by driesvints** [comment]
Let's wait and see if this one gets accepted first

**Pull request merged**
