### PR TITLE
[6.x] Document gotcha with local filesystem driver url() method.

### PR DESCRIPTION
**Pull request by LukeTowers**
Related: https://github.com/laravel/framework/pull/34237#issuecomment-691469104

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you just send this to the current docs.

**Comment by LukeTowers** [comment]
@taylorotwell @driesvints don't know if you know this, but it takes all of two seconds to make that change yourself, see the "base: develop" dropdown when you click the edit button next to the PR title. 

I'm not going to bother resubmitting this given that this is now the third interaction I've had to have regarding this issue and I don't care enough to attempt a fourth time. Feel free to re-open and change the base branch yourself.
Screen Shot 2020-09-14 at 9 52 40 AM

**Comment by driesvints** [comment]
@LukeTowers changing the base branch ourselves could lead to having unwanted commits travelling along.

**Comment by LukeTowers** [comment]
@driesvints I would recommend at least trying it first before auto closing PRs. It takes two seconds of time to prevent requiring potentially 10 minutes of the contributor's time. 

Personally I also recommend defaulting to squashing commits anyways but how you choose to manage these repositories is your choice.

**Comment by driesvints** [comment]
@LukeTowers that's because I mostly know what goes into these repos because I also try to check in on each PR. So I know there would be conflicts.

See https://github.com/laravel/docs/compare/8.x...6.x

**Comment by driesvints** [comment]
Sent in your PR here: https://github.com/laravel/docs/pull/6368

Thanks

**Pull request closed without merging**
