### PR TITLE
[5.3] Mention authorizeResource method

### PR DESCRIPTION
**Pull request by Anahkiasen**
Very helpful method, wish I had known about it sooner :D

### CODE REVIEW

**Comment by taylorotwell** [comment]
I think this would be more helpful with maybe a table of exactly what equivalent middleware it adds.

**Comment by Anahkiasen** [comment]
Good idea, going to add that

**Comment by taylorotwell** [comment]
Please submit this to 5.4 branch of docs.

**Comment by Anahkiasen** [comment]
@taylorotwell We can update the base branch of a PR without closing it now, updated the PR. Or do you want me to reopen a new one?

**Pull request closed without merging**
