### PR TITLE
add notes for elasticsearch installation

### PR DESCRIPTION
**Pull request by browner12**
relevant PR: https://github.com/laravel/homestead/pull/683

### CODE REVIEW

**Comment by taylorotwell** [comment]
Removed note about dropping ES to 1GB of memory because you mention it but don't actually show how to do it.

**Comment by browner12** [comment]
yah, we haven't made it customizable through the `Homestead.yaml` yet, so user would have to do it manually in the terminal.

**Comment by zanematthew** [comment]
Are there additional steps/notes coming? Or is it expected that after you've added `elasticsearch: true` and have done a `vagrant provision`, you'll be able to ping the server at `http://localhost:9200`?

Looking forward to this.

**Comment by zanematthew** [comment]
...also FWIW, I have this running within Homestead. I just edited my elasticsearch.yml at `/etc/elasticsearch/elasticsearch.yml`, just wasn't sure if that step is/was expected.

**Comment by browner12** [comment]
this is all you need to start up.

you are welcome to customize the install to your needs, but this will get most people up with a simple ES install.

**Comment by zanematthew** [comment]
First, thank you for this PR. 

I've enjoyed playing with Laravel and Elasticsearch on nights and weekends, its been a joy.

Your PR adds Elasticsearch 5.6.3, however Elasticsearch 6.0 was released [4 days ago](https://github.com/elastic/elasticsearch/releases) and contains a number of [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking-changes-6.0.html), primarily the removal of [mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html).

Are there any plans to support Elasticsearch updates within Homestead?

Additionally, wouldn't the breaking change to no longer support mapping types effect Laravel Scout?

**Pull request merged**
