### PR TITLE
Added Mcrypt to requirements

### PR DESCRIPTION
**Pull request by vjandrea**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
This is incorrect. It's no longer required in 5.1. Infact, the only thing that uses it is deprecated.

**Comment by vjandrea** [comment]
@GrahamCampbell i just deployed a 5.1.26 on a host that doesn't support mcrypt and i see plenty of exceptions like this:
“**RuntimeException** in *EncryptionServiceProvider.php* line 29: No supported encrypter found. The cipher and / or key length are invalid.”
Do you have any suggestion, apart from enabling Mcrypt?

**Comment by GrahamCampbell** [comment]
> Do you have any suggestion, apart from enabling Mcrypt?

Yes, correct you encryption config.

**Comment by GrahamCampbell** [comment]
> apart from enabling Mcrypt?

That is only there for really old Laravel 4 apps to still work. We're removing it at some point.

**Comment by vjandrea** [comment]
Thanks for the info, i had lost this commit: https://github.com/laravel/laravel/commit/f0cad014cf5b8db69adc93854a25a5792b8e3a7e, actually started the project earlier than june.

**Comment by GrahamCampbell** [comment]
Just a note that we've finally removed the mcrypt gallback in L5.3, which is due to ship in June 2016.

**Pull request closed without merging**
