### PR TITLE
[9.x] Add docs for S3 `temporaryUploadUrl()` method

### PR DESCRIPTION
**Pull request by aneeskhan47**
Docs for PR: https://github.com/laravel/framework/pull/45753

### CODE REVIEW

**Comment by aneeskhan47** [comment]
#45753

**Comment by aneeskhan47** [comment]
@taylorotwell Since you merged the main PR into the framework 😎❤, Can you look into this and make any changes that you see. like grammar etc.  😅

**Comment by aneeskhan47** [comment]
> @taylorotwell Since you merged the main PR into the framework 😎❤, Can you look into this and make any changes that you see. like grammar etc. 😅

I mean like mentioning vapor serverless uploads etc. the required headers thing

**Comment by taylorotwell** [comment]
@aneeskhan47  I have no idea why the entire table of contents is changed?

**Comment by aneesdev** [comment]
> @aneeskhan47 I have no idea why the entire table of contents is changed?

Sorry, I think my vs code did the auto markdown formatting.

**Comment by aneeskhan47** [comment]
@taylorotwell now its fixed 😊

**Comment by taylorotwell** [comment]
Documented on 10.x docs.

**Pull request closed without merging**
