### PR TITLE
[6.x] Fix broken images

### PR DESCRIPTION
**Pull request by driade**
https://res.cloudinary.com/dtfbvvkyp/image/upload/v1537195039/photos/Test.png is broken

### CODE REVIEW

**Comment by driesvints** [comment]
Just send in the correct link

**Comment by taylorotwell** [comment]
I'm not adding all caps BROKEN to the docs.

**Comment by driade** [comment]
I'm sorry I cannot determine which is the correct link to the image, I though this was the best way for you find the one you should upload to laravel.com, as of https://github.com/laravel/docs/pull/6307

**Comment by driade** [comment]
May this one be the correct image?

Test

**Pull request closed without merging**
