### PR TITLE
Added 'The Public Disk' section

### PR DESCRIPTION
**Pull request by gqrdev**
Adds how to create a symlink when using the public disk.

### CODE REVIEW

**Comment by ahinkle** [comment]
This doesn't really specialize in the specifics of Laravel Sail. Developers can find detailed documentation on file storage in https://laravel.com/docs/10.x/filesystem#the-public-disk - this would be a bit out of place.

**Comment by gqrdev** [comment]
I have removed unnecessary text from my contribution.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by taylorotwell** [comment]
Not sure these instructions are super clear.

**Pull request closed without merging**
