### PR TITLE
[8.x] Adds disclaimer to breeze install command

### PR DESCRIPTION
**Pull request by fylzero**
Suggesting to add this since it seems to have caused someone some grief recently, per this post.

[https://laracasts.com/discuss/channels/laravel/careful-laravel-commands-are-not-careful](https://laracasts.com/discuss/channels/laravel/careful-laravel-commands-are-not-careful)

There isn't an explicit warning against adding this to existing projects, which may be useful.

### CODE REVIEW

**Comment by driesvints** [comment]
I'm not sure if this is needed. It's documented under "starter kits" which should be indicative enough that this is for new installs only. The first sentence of the introduction also states:

> To give you a head start building **your new Laravel application,** we are happy to offer authentication and application starter kits.

**Comment by fylzero** [comment]
@driesvints I think you're right but also, being that this particular kit is geared towards the absolute beginner maybe stating that explicitly isn't the worst idea.  There might be a less abrupt/verbose way of adding that than what I am presenting here.

**Comment by fylzero** [comment]
Thinking about this more and looking at the docs it should be sufficient to state that it is a starter kit, also the instructions clearly say the first step of installing is to create a fresh application.  Not to mention a big warning on a beginner starter kit page claiming death and destruction is probably not ideal...  closing.

**Comment by driesvints** [comment]
@fylzero still appreciate you trying to help out here with improving these docs :)

**Pull request closed without merging**
