### PR TITLE
Documentation on Blade's directive() helper

### PR DESCRIPTION
**Pull request by franzliedke**
As requested in https://github.com/laravel/framework/pull/8425.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you show the generated raw PHP output of the example?

**Comment by franzliedke** [comment]
You mean the PHP code of the compiled template?

**Comment by taylorotwell** [comment]
Right.

**Comment by franzliedke** [comment]
Thanks for the heads-up, I had to fix it.

This code:

    Blade::directive('datetime', function($expression) {
        return "<?php echo {$expression}->format('m/d/Y H:i'); ?>";
    });

For this Blade template:

    @datetime($foo)

Results in this PHP:

    <?php echo ($foo)->format('m/d/Y H:i'); ?>

**Comment by taylorotwell** [comment]
Is that `echo ($foo)->` syntax even valid? That doesn't even parse for me and I've never seen syntax like that.

**Comment by taylorotwell** [comment]
Seems like you would need something like `with{$expression}->format` which would turn into `with($foo)->format()`

**Comment by franzliedke** [comment]
Ah, you're right. This [would only work in PHP 7](http://3v4l.org/B9rAH).

I just changed it to use `with()`. Or should we change the code so that the parenthesis won't be sent to the closure as they're implicit?

**Comment by TheShiftExchange** [comment]
...so is this also valid syntax?

```
Blade::directive('datetime', function($expression, $format) {
    return "<?php echo {$expression}->format($format); ?>";
});
```

For this Blade template:

```
@datetime($foo, 'd-m-Y')
```

Results in this PHP:

```
<?php echo ($foo)->format('d-m-Y'); ?>
```

**Comment by franzliedke** [comment]
@TheShiftExchange No, that would only work in PHP 7. You should do this:

```php
Blade::directive('datetime', function($expression, $format) {
    return "<?php echo with{$expression}->format($format); ?>";
});
```

**Pull request merged**
