### PR TITLE
minor English language update / typo

### PR DESCRIPTION
**Pull request by geo4orce**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please squash to one commit.

**Comment by geo4orce** [comment]
I understand, wanted to do it myself, but didn’t know how :-(

Found this answer seems to have done the trick (both changes are in a 
single commit now). 

git reset --soft HEAD~2
But the PR now has 5(!) commits total :-\





From:  Graham Campbell
Reply-To:  laravel/docs
Date:  Saturday, July 18, 2015 at 1:03 PM
To:  laravel/docs
Cc:  "geo.artemenko@gmail.com"
Subject:  Re: [docs] minor English language update / typo (#1689)


Please squash to one commit.

**Comment by GrahamCampbell** [comment]
Now there are 5 commits, not 3...

**Comment by geo4orce** [comment]
right, like I just mentioned. What would be a good way to merge it all into one? delete my repo and fork again? then apply the changes one at a time and commit them together?

**Pull request merged**
