### PR TITLE
Insert missing parentheses.

### PR DESCRIPTION
**Pull request by paulboco**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
These are not missing, please close this.

**Comment by paulboco** [comment]
If it is not intended for parentheses to be present, then why does the final PHP generated by this directive (shown on last line of this file) contain parentheses?

**Comment by GrahamCampbell** [comment]
Because the $expression variable already has the parentheses in it...

**Comment by paulboco** [comment]
Cool. Thanks. I guess I don't understand how this works. Perhaps the example could reflect that.

**Comment by GrahamCampbell** [comment]
Looking at the regex under the hood might help you understand. :)

**Comment by paulboco** [comment]
Ok. Will do.

**Pull request closed without merging**
