### PR TITLE
[6.x] Update installation.md

### PR DESCRIPTION
**Pull request by timgreenwood**
Updated Composer's system-wide vendor bin directory for updated Laravel installer from $HOME/.composer/vendor/bin to $HOME/.config/composer/vendor/bin

### CODE REVIEW

**Comment by driesvints** [comment]
My composer isn't located here but maybe the default got changed? Can you link to any Composer documentation that proves that this is the new default location?

**Comment by timgreenwood** [comment]
https://getcomposer.org/doc/03-cli.md#composer-home

I think it is due to this line:

**Comment by driesvints** [comment]
Which line is that?

**Comment by timgreenwood** [comment]
> Which line is that?

Sorry, I hit cmd+return by accident - reply updated

**Pull request merged**
