### PR TITLE
Warn about .env values with spaces

### PR DESCRIPTION
**Pull request by tomcastleman**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Feel like this should maybe be in the config section.

**Comment by tomcastleman** [comment]
@taylorotwell could you clarify whether you mean I should add this to the config docs in addition or instead of in the upgrade guide? I can add it to the configuration docs too, but I added it here because it is a breaking change between 5.1 and 5.2 (between `vlucas/phpdotenv` v1 and v2).

Thanks

**Comment by tomcastleman** [comment]
A little frustrating this has been closed with no decent feedback. Any thoughts @GrahamCampbell ?

**Comment by tomcastleman** [comment]
@GrahamCampbell Following on from [your comment](https://github.com/laravel/framework/issues/11715#issuecomment-204737355), what further context to can I provide on this? We just need to put something in along these lines so give me something to go on or just add it in yourself.

**Comment by tomcastleman** [comment]
The complete lack of response on this is disappointing.

**Comment by philbates35** [comment]
I fell victim to this last week. The resulting stacktrace has no mention of an invalid value in the `.env` file either, so it took far too long to work out what was wrong.

**Pull request closed without merging**
