### PR TITLE
More information for Horizon that not support Redis Cluster very well

### PR DESCRIPTION
**Pull request by miaotiao**
Some people might not use Redis cluster mode when they see this information

### CODE REVIEW

**Comment by taylorotwell** [comment]
Not a very detailed comment.

**Comment by miaotiao** [comment]
> Not a very detailed comment.

I am sorry I did not describe it detailed.

As Horizon cannot perfectly support Redis Cluster, we should tell people who use Horizon in the documentation not to use Redis Cluster to avoid troubleshooting later.

**Comment by miaotiao** [comment]
@taylorotwell 

Evidence that Horizon does not support Redis Cluster well.

You said [it](https://github.com/laravel/horizon/issues/274#issuecomment-457218217)

**Comment by vicandam** [comment]
Yes @taylorotwell please include it on horizon documentation that redis cluster does not support redis cluster. I've spent several days troubleshooting my application until found it [here](https://github.com/laravel/horizon/issues/274#issuecomment-457218217)

**Comment by mavci** [comment]
> Yes @taylorotwell please include it on horizon documentation that redis cluster does not support redis cluster. I've spent several days troubleshooting my application until found it [here](https://github.com/laravel/horizon/issues/274#issuecomment-457218217)

Same here. I wish I had learned this sooner, but on the bright side, I learned in detail how Redis Cluster works because of this error.

**Pull request closed without merging**
