### PR TITLE
Add note about @stop directive

### PR DESCRIPTION
**Pull request by mdavis1982**
Add a note about using `@stop` interchangeably with `@endsection`.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Ah OK, for this one I think I don't show it because when I wrote 5.3 docs I decided to just typically show 1 way to do things instead of showing several different ways to do the same thing. It just makes the docs more streamlined and simple. I think the other things you mentioned on Twitter are more needed in the documentation though.

**Comment by mdavis1982** [comment]
@taylorotwell sure, but it's confusing when you see people using it (@jeffreyway uses it a lot on his videos), and it's not in the documentation

**Comment by taylorotwell** [comment]
Ah, wasn’t aware that it was showing up in videos a lot. OK will reconsider that

**Comment by JeffreyWay** [comment]
Haha - Yeah I've used @stop for years. Just habit. I can switch over to @endsection.

**Comment by mdavis1982** [comment]
Cool... Either works 😄 

I'm digging into Blade a lot in preparation for an upcoming project which is how I noticed that these directives weren't in the documentation. Lots of source diving done today!

**Comment by tkaw220** [comment]
@mdavis1982 Mind to share which source code files you dig for hidden Blade gem?

**Comment by mdavis1982** [comment]
@tkaw220 Sure... I've been spending a lot of time in here: https://github.com/laravel/framework/blob/5.3/src/Illuminate/View/Compilers/BladeCompiler.php

**Pull request closed without merging**
