### PR TITLE
Clarified retrieveByCredentials and validateCredentials methods

### PR DESCRIPTION
**Pull request by dustinalan**
Added return information for retrieveByCredentials and validateCredentials when extending UserProviderInterface

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please resend to 5.0.

**Comment by dustinalan** [comment]
I was asked to merge it into 4.2, then Master, now 5.0. Graham, you should be able to merge this from the patch I provided. Or grant me access to the project and I'll add it to 5.0 as a commit. It's only 2 sentences.

**Comment by GrahamCampbell** [comment]
It needs to be sent to the docs for the current stable. That was 4.2. Time has moved on, and it's now 5.o.

**Comment by dustinalan** [comment]
I'll submit again since it seems the pull was between a version release. In case I contribute again, is the project working off master or current stable (now 5.0)? I didn't see a contributing document which would typically explain this in detail.

**Pull request closed without merging**
