### PR TITLE
The composer dir changed, this should be modified

### PR DESCRIPTION
**Pull request by RryLee**

### CODE REVIEW

**Comment by taylorotwell** [comment]
This has been brought up several times but I'm still a little confused by it. I use Composer on Mac and don't have any such directory.

**Comment by arcanedev-maroc** [comment]
I've the `.config` directory but no `composer` folder in it. I'm on Windows 8.0.

**Comment by sebastiaanluca** [comment]
Had this issue a while ago on a new Homestead VM. Also, the Composer docs do specify a new directory.

**Comment by willrowe** [comment]
I ran into this issue a month or so ago. Either `~/.config/composer/vendor/bin` and `~/.composer/vendor/bin` can be used, it just depends on the environment. I think I figured out it had something to do with whether the `XDG_CONFIG_HOME` environment variable was set (which is usually `~/.config`.

**Comment by RryLee** [comment]
Oh, i know. thank you guys

**Pull request closed without merging**
