### PR TITLE
[11.x] Document Paddle's bill for non-catalog items feature

### PR DESCRIPTION
**Pull request by AcTiv3MineD**
Documentation for the newly added functionality of non-catalog items on Cashier paddle: https://github.com/laravel/cashier-paddle/pull/263

### CODE REVIEW

**Comment by taylorotwell** [comment]
This doesn't follow the capiatlization / title guidelines of rest of docs.

**Comment by AcTiv3MineD** [comment]
@taylorotwell Where can I find the guidelines to apply it?

**Comment by AcTiv3MineD** [comment]
Applied Title Case

**Comment by RobertoGongora** [comment]
@AcTiv3MineD It's better to create a new PR so Taylor gets the notification, good luck!

**Comment by AcTiv3MineD** [comment]
> @AcTiv3MineD It's better to create a new PR so Taylor gets the notification, good luck!

Hi @RobertoGongora , thanks for the suggestion!

I think they have some sort of system to track open PRs.

Maybe he needs more time or decided to check again later and that's ok. No rush.

But, in case I see no response in a couple of days I may apply your suggestion as it can be the reason.

**Comment by taylorotwell** [comment]
These docs don't really explain what to do or what happens. What am I supposed to do with $checkout on my frontend in the Blade view, etc?

**Comment by taylorotwell** [comment]
There are a lot of issues with these docs so going to close for now.

**Comment by carlosmintfan** [comment]
Planning to check and reopen this. :smile:

**Pull request closed without merging**
