### PR TITLE
[9.x] Adds doc for the `PendingCommand@execute`

### PR DESCRIPTION
**Pull request by sethsandaru**
Related to this https://github.com/laravel/framework/issues/45811, the method needs to be documented so it won't confuse people

### CODE REVIEW

**Comment by sethsandaru** [comment]
@taylorotwell @driesvints please lemme know if I need to update the text 😄

**Comment by taylorotwell** [comment]
I don't think this is accurate? For example, the following test passes on a empty, new Laravel project:

```php
$this->artisan('inspire');

$this->assertDatabaseMissing('users', ['email' => 'taylor@laravel.com']);
```

**Comment by sethsandaru** [comment]
@taylorotwell assertDatabaseMissing would work normally fine because there won't be any insertion happened 🤔

**Comment by sethsandaru** [comment]
So that's why we had the issue reported and this is the solution https://github.com/laravel/framework/issues/45811#issuecomment-1404767567

IMO it is fine to add the doc for `execute` too, since there is no place mentioned that (unless you are using PHPStorm and figure the method yourself)

**Pull request closed without merging**
