### PR TITLE
Add phpunit path explanation

### PR DESCRIPTION
**Pull request by CausaMortis**
found myself Googling this several times. Might as well save others the hassle by being explicit

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Laravel does not recommend global installs.

**Comment by CausaMortis** [comment]
ok so can we at least explain that you should be using the full path to the binary rather than calling the alias?

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by CausaMortis** [comment]
is there anything I need to do in order to include this in the other branches going back to 4.2 as well?

**Comment by gmsantos** [comment]
@GrahamCampbell Laravel doesn't recommend only for phpunit, right?

For Laravel Installer it does recommend global installation:

https://laravel.com/docs/5.2/installation

**Comment by taylorotwell** [comment]
Going to hold off on this.

**Pull request closed without merging**
