### PR TITLE
Document collection methods

### PR DESCRIPTION
**Pull request by JosephSilber**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This page now feels very big. Maybe we need to break it up a bit?

**Comment by JosephSilber** [comment]
@GrahamCampbell I don't think so. There isn't really any logical grouping to them.

Who cares that it's a big page. It's a list of method definitions.

I think it's just fine the way it is. Easy to find everything in one place.

**Comment by lagbox** [comment]
I'm glad someone put it together. :)

**Comment by GrahamCampbell** [comment]
@JosephSilber I don't really agree. If you want one place, look at the documentation in the source, and the tests for the class.

**Comment by psampaz** [comment]
I agree @JosephSilber. No one will care that this is a big page. 

Everyone will love to see this in the docs. 

Good job Joseph!

**Comment by brunogaspar** [comment]
:+1: @JosephSilber

**Pull request merged**
