### PR TITLE
[10.x] Adding MailerSend as an option for Mail driver

### PR DESCRIPTION
**Pull request by fosron**
Hey, I am Tautvydas, Lead Developer at transactional email service https://www.mailersend.com/ and we are looking into applying as one of mail drivers mentioned [here](https://laravel.com/docs/10.x/mail#driver-prerequisites). We have a [package ready](https://github.com/mailersend/mailersend-laravel-driver), and used by our clients, we are also working into having our Mailer library merged into [Symfony 6.3](https://github.com/symfony/symfony/pull/49461). We are a Laravel-first house, most of our projects rely on it, so we feel like we can also help wider community. We provide a [generous free plan](https://www.mailersend.com/pricing) and several good and helpful features, that would add value to everyone using Laravel and trying to get their email delivered.

_I asked for opinions first at #internals on Laravel Discord. If needed, we can resume discussion there. Thanks_

### CODE REVIEW

**Comment by taylorotwell** [comment]
Let me think about this a bit. It would be uncommon for us to document third-party packages like this. Thank you!

**Comment by jonnott** [comment]
Feels like this should only be documented here *if* the package gets integrated into Symfony, which would put it on a level footing with other documented integrations via Symfony.

However, if/once it were to get into Symfony, it would feel like favouritism towards the other (commercial) services documented to not include MailerSend also.

**Comment by fosron** [comment]
As of yesterday MailerSend [mail driver](https://symfony.com/doc/current/mailer.html) has been officially released as part of Symfony 6.3. Could we get a reconsideration for being included into Laravel documentation? Thank you.

**Comment by Agathe-Brusset** [comment]
Hello @taylorotwell, as shared by @fosron , we have been implemented into Symfony in their 6.3 release, and we hoped to be included in Laravel along with Mailgun and Postmark. Please let us know if this is doable!
Thank you.

**Comment by taylorotwell** [comment]
Done: https://github.com/laravel/docs/commit/ebefbe94c1a3dd008e15b4951e2574ba39be3acc

Thanks 👍

**Pull request closed without merging**
