### PR TITLE
[7.x] Fix methods order and add 2 missing ones for `Arr` helper

### PR DESCRIPTION
**Pull request by denis-korchagin95**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Q comes before R and S?

**Comment by denis-korchagin95** [comment]
> Q comes before R and S?

Yeah, I don't understand a little logic of placement too, because in original branch Q after R. So, I think what order of methods reflects the order in the source code and I fixed it to be the same.

**Comment by taylorotwell** [comment]
That ordering doesn't make sense. Please just PR your additional only and put them in alphabetical order for now.

**Comment by denis-korchagin95** [comment]
> That ordering doesn't make sense. Please just PR your additional only and put them in alphabetical order for now.

Ok.

**Pull request closed without merging**
