### PR TITLE
Update markdown tables

### PR DESCRIPTION
**Pull request by TENIOS**
I "freshened up" the tables and fixed some, such as those that were too long and indented (`contracts.md`). Many tables have become more readable for documentation developers.

Please don't close the PR, I'm willing to fix or put some changes back in. I've done a lot of work and I don't want it to just disappear.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I need before and after screenshots of the changes.

**Comment by TENIOS** [comment]
> I need before and after screenshots of the changes.

What does it look like on the website?

**Comment by TENIOS** [comment]
I took screenshots of only those tables that have changed on the site. Those that have no changes, I did not take a screenshot because they contain changes only in Markdown.

### Contracts

| Before | After |
| --- | --- |
| contracts-before{: width="50%"} | contracts-after{: width="50%"} |

### Facades

| Before | After |
| --- | --- |
| facades-before{: width="50%"} | facades-after{: width="50%"} |

### Logging

| Before | After |
| --- | --- |
| logging-before{: width="50%"} | logging-after{: width="50%"} |

### Mail

| Before | After |
| --- | --- |
| mail-before{: width="50%"} | mail-after{: width="50%"} |

### Migrations

| Before | After |
| --- | --- |
| migrations-before{: width="50%"} | migrations-after{: width="50%"} |

### Notifications

| Before | After |
| --- | --- |
| notifications-before{: width="50%"} | notifications-after{: width="50%"} |

### Scheduling

| Before | After |
| --- | --- |
| scheduling-before{: width="50%"} | scheduling-after{: width="50%"} |

Well. That was a long time coming.

(I know that `{: width=“50%”}` has no effect, but without them the right photo is always smaller.)

**Comment by TENIOS** [comment]
If you open each screenshot, you'll notice that dots have appeared at the end of sentences where they weren't, and also the unnecessary semicolon in **Contracts** after `Illuminate\Contracts\Pipeline\Pipeline` has been removed.

**Comment by TENIOS** [comment]
You can make sure that all tables are displayed correctly by use command in cloning `laravel.com` repository:

```sh
git clone --single-branch --branch "update-tables" https://github.com/TENIOS/docs "resources/docs/11.x"
```

**Comment by TENIOS** [comment]
I also noticed that some tables are missing `div` with class `overflow-auto` because of what on mobile devices the page is displayed incorrectly.

It's not due to my changes you can check it out at [Contracts](https://laravel.com/docs/11.x/contracts) page in production.

**Comment by TENIOS** [comment]
@taylorotwell, thanks.

**Pull request merged**
