### PR TITLE
DB Read's and Write's Hosts should be an array

### PR DESCRIPTION
**Pull request by itsromack**
Configuration for the database hosts for the read and/or write resource should be an array

### CODE REVIEW

**Comment by decadence** [comment]
@itsromack can you explain why?

**Comment by connectkushal** [comment]
@itsromack can you explain why?

**Comment by itsromack** [comment]
@decadence @connectkushal due to the possibility of multiple database replicas and slaves

**Comment by connectkushal** [comment]
thnx

**Pull request merged**
