### PR TITLE
Update routing.md

### PR DESCRIPTION
**Pull request by shtukas**
Added missing word "loaded" in first sentence.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please close this since #2007 already exists. You only need to send one PR. ;)

**Comment by shtukas** [comment]
Ok cool :-)

**Comment by shtukas** [comment]
@GrahamCampbell 

The correction I submitted to the branch 5.2 has been merged, but the one I had submitted to master, which you asked me to close, is resulting in the typo still being present in the master branch. I am reopening the pull request.

**Comment by GrahamCampbell** [comment]
Please close this one.

**Comment by GrahamCampbell** [comment]
We will do branch merges 5.2->master. No need to send two PRs.

**Comment by shtukas** [comment]
Hi Graham, Ok, I will close it, but please note that I was simply following the repo's own instructions 

"If you are submitting documentation for the current stable release, submit it to the corresponding branch. For example, documentation for Laravel 5.1 would be submitted to the 5.1 branch. Documentation intended for the next release of Laravel should be submitted to the master branch."

Cheers,

**Comment by GrahamCampbell** [comment]
> "If you are submitting documentation for the current stable release, submit it to the corresponding branch. For example, documentation for Laravel 5.1 would be submitted to the 5.1 branch. Documentation intended for the next release of Laravel should be submitted to the master branch."

Those instructions say only send to the lowest branch. They don't say send to more than one branch.

**Comment by shtukas** [comment]
I see, I undertand now. Thanks! Instructions were.... partially ambiguous. Cheers,

**Pull request closed without merging**
