### PR TITLE
[6.0] Added additional step to setup PHP Redis

### PR DESCRIPTION
**Pull request by DarkGhostHunter**
[Fixes #29806](https://github.com/laravel/framework/issues/29806)

### CODE REVIEW

**Comment by taylorotwell** [comment]
We throw an informative error now, so I don't think this is necessary.

**Comment by DarkGhostHunter** [comment]
> We throw an informative error now, so I don't think this is necessary.

So, we must expect the developer finds this error in production when changing the driver to `phpredis`?

**Comment by driesvints** [comment]
@DarkGhostHunter we got this merged 👍

**Comment by DarkGhostHunter** [comment]
Yay! 😄

**Pull request merged**
