### PR TITLE
Filesystem section: Cloud filesystem disk and linking stored files

### PR DESCRIPTION
**Pull request by pjmartorell**
- Add explanation of how to get the URL of a given stored file
- Add Cloud filesystem disk explanation
- Fix text since filesystems config samples are actually included with the framework's default 'filesystems.php' config file

### CODE REVIEW

**Comment by pjmartorell** [comment]
Hi @taylorotwell , what do you think about adding this to the Filesystem / Cloud Storage section?

**Comment by pjmartorell** [comment]
@taylorotwell ?

**Comment by pjmartorell** [comment]
@taylorotwell ?

**Comment by taylorotwell** [comment]
Some of this info isn't correct. A sample of the FTP config isn't included with the framework.

**Comment by pjmartorell** [comment]
@taylorotwell Yes, it's included in Laravel 5.2, but not in master branch. Check the part of the source code of Laravel 5.2 I'm referering to, [here](https://github.com/laravel/laravel/blob/v5.2.0/config/filesystems.php#L51-L71).

Thanks

**Comment by pjmartorell** [comment]
Well, now I have seen your commit [85e6774](https://github.com/laravel/laravel/commit/85e6774d2ec7badaa0924f9d45635cd204cc9093#diff-7b9241412b3dab19230761bbdde0b3c8) where you simplified filesystem default configuration in Laravel 5.2.29, so neither Rackspace nor FTP configurations are included. I will do a new pull request taking Laravel 5.2.29 as a reference. Thanks

**Pull request closed without merging**
