### PR TITLE
Add tip how to disable failed jobs database logging

### PR DESCRIPTION
**Pull request by CodeTechNL**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Not entirely accurate - I will fix it.

**Comment by taylorotwell** [comment]
Had to make a slight change to the framework to make this all work a little better, actually.

**Comment by CodeTechNL** [comment]
@taylorotwell so setting that config value to `null` doesn't stop registering failed jobs?

**Comment by taylorotwell** [comment]
No I don't think so - it may just be triggering an error that is silent or in your logs.

**Comment by CodeTechNL** [comment]
What is the good way to solve this? I don't want to log the failed jobs to the database, any idea for me?

**Pull request closed without merging**
