### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by andreich1980**
Found 2 broken anchors in the `queues.md` with my script https://gist.github.com/andreich1980/a58deabb237e13c162b581530d262b93

### CODE REVIEW

**Comment by driesvints** [comment]
Can you send this to 8.x?

**Comment by andreich1980** [comment]
@driesvints 8.x doesn't have this problem. It only exists on master.
I have checked it before sending the PR.
Please consider checking it yourself.

**Comment by driesvints** [comment]
I've merged 8.x into master which should fix this.

**Comment by andreich1980** [comment]
Yes, seems everything is good in master and 8.x now. Thanks @driesvints

**Pull request closed without merging**
