### PR TITLE
documents devcontainer support

### PR DESCRIPTION
**Pull request by videlalvaro**
Documents new devcontainer parameter added here https://github.com/laravel/sail-server/blob/master/routes/web.php#L25

### CODE REVIEW

**Comment by videlalvaro** [comment]
@driesvints @taylorotwell updated the install docs to document this new feature, thanks!

**Comment by taylorotwell** [comment]
Thanks for contributing to Laravel! ❤️

**Comment by videlalvaro** [comment]
@taylorotwell thanks for the prompt merge! Do you know when this should go live?

**Comment by driesvints** [comment]
@videlalvaro should be live by now

**Pull request merged**
