### PR TITLE
[5.6] Document onceBasic() throwing exception

### PR DESCRIPTION
**Pull request by jansennerd10**
https://github.com/laravel/docs/pull/5005

### CODE REVIEW

**Comment by ahinkle** [comment]
5.6 is unsupported. Please review [the support policy](https://laravel.com/docs/releases) on which versions the maintainers currently supporting.

**Comment by ahinkle** [comment]
5.6 is unsupported. Please review [the support policy](https://laravel.com/docs/releases) on which versions the maintainers are currently supporting.

**Comment by taylorotwell** [comment]
There is nothing actually wrong with the current code.

**Comment by jansennerd10** [comment]
The documentation is still incorrect when it states that "if no response is returned... the request may be passed further into the application."

Plus, you specifically requested this PR, and merged the exact same one (minus the upgrade notes) into 5.5.

**Comment by jansennerd10** [comment]
@taylorotwell could you take a second look at this? I think you overlooked the important part.

I spent some time trying to find the problem (documented at https://github.com/laravel/framework/issues/27633) and I'm trying to save others that time.

**Comment by driesvints** [comment]
@jansennerd10 just send in a new pr without the code changes

**Pull request closed without merging**
