### PR TITLE
Added note about versioned files in css being replaced in production

### PR DESCRIPTION
**Pull request by imerr**
I had trouble finding any documentation about that behaviour and I probably won't be the only one with that issue

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't know what this means.

**Comment by imerr** [comment]
When you want to version images for example with elixir for cache busting and you reference those images in stylesheets (background images for example) it replaces the unversioned image path with the versioned one when you run gulp in production mode

That behaviour is documented nowhere as far as I could see

**Comment by michaeldyrynda** [comment]
You should just use the `elixir` helper function in your views, which is documented in the paragraph above where you [added this change](https://laravel.com/docs/5.3/elixir#versioning-and-cache-busting).

> Once the files have been versioned, you may use the elixir helper function to generate links to the proper hashed files.

**Comment by imerr** [comment]
I am not talking about views
I am talking about css files (/stylesheets)

**Comment by michaeldyrynda** [comment]
Ah, right, I misread. If they're automatically adjusted in your stylesheets, this isn't a problem, you're just documenting the existing behaviour?

**Comment by imerr** [comment]
exactly

**Pull request closed without merging**
