### PR TITLE
chain ->getValue(DB::connection()->getQueryGrammar()) to DB::raw()

### PR DESCRIPTION
**Pull request by jonnott**
..calls in the docs, as per upgrade guide

### CODE REVIEW

**Comment by jonnott** [comment]
Hmmm .. after debugging this in my own apps, I think I've got the wrong end of the stick here .. I think (correct me if I'm wrong), you only need getValue() if you're adding the output of an expression into some of raw SQL or other string. If it's going straight into e.g. a select() or addSelect(), you can still just use plain DB::raw() ?

**Comment by jonnott** [comment]
"Database "expressions" (typically generated via DB::raw) have been rewritten in Laravel 10.x to offer additional functionality in the future."

@driesvints @taylorotwell Can we get a sneak of what that functionality is?

**Comment by driesvints** [comment]
Think @tpetry worked on this?

**Comment by tpetry** [comment]
@jonnott You are getting the idea for them from my pr: [[10.x] database expressions with grammar-specific formatting](https://github.com/laravel/framework/pull/44784)

I am right now working on [tpetry/laravel-query-expressions](https://github.com/tpetry/laravel-query-expressions) to provide a lot of ready-made expressions. But its a lot of work to identify all the changes of different database versions and finding ways to harmonize their behaviour to work exactly the same on all of them.

**Pull request closed without merging**
