### PR TITLE
Add/remove commas to improve sentence flow

### PR DESCRIPTION
**Pull request by ssfinney**
I've removed some unnecessary commas and added others to improve sentence flow throughout the documentation.

I used [Grammarly](http://www.grammarly.com) to ensure that these changes agree with English comma rules.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
All the comma removals before `and` are wrong.

**Comment by GrahamCampbell** [comment]
We're using the Oxford comma.

**Comment by GrahamCampbell** [comment]
> I used Grammarly to ensure that these changes agree with English comma rules.

Those checks are wrong then.

**Comment by ssfinney** [comment]
You're correct, sorry

**Pull request closed without merging**
