### PR TITLE
Increment version of laravel/installer

### PR DESCRIPTION
**Pull request by MarkRedeman**
Increment the version of `laravel/installer` to version `1.2`.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
`~1.1` will install 1.2.x.

**Comment by GrahamCampbell** [comment]
TBH, we should just change this to `composer global require "laravel/installer`.

**Comment by MarkRedeman** [comment]
Oh yeah, I forgot about the `~` rule.

:+1:  for changing it to `composer global require laravel/installer` (is there a reason why the command currently includes the version?).

**Comment by GrahamCampbell** [comment]
> (is there a reason why the command currently includes the version?).

I think it was just there to help people know what the current version is, but I don't think that information is very useful personally.

**Comment by MarkRedeman** [comment]
I agree. Shall I change the pull request to omit the version number?

**Comment by GrahamCampbell** [comment]
I think so, yeh. :)

**Pull request merged**
